/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormGerenciarAlterarSenha extends javax.swing.JDialog {
    
    private String username;

    /**
     * Creates new form FormGerenciarAlterarSenha
     */
    public FormGerenciarAlterarSenha(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents();
        
        try {
            
            com.sys.SystemSettings.setSystemThemeNimbus();
            
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
        setSize(410, 155);
        setLocationRelativeTo(null);
        
    }
    
    public void setUsername(String username) {
        
        this.username = username;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblSenha = new javax.swing.JLabel();
        jpwdSenha = new javax.swing.JPasswordField();
        jlblConfirmeSenha = new javax.swing.JLabel();
        jpwdConfirmeSenha = new javax.swing.JPasswordField();
        jsepRodape = new javax.swing.JSeparator();
        jbtnAlterar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CadHab - Alterar Senha de Usuário");
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jlblSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSenha.setText("Senha:");
        getContentPane().add(jlblSenha);
        jlblSenha.setBounds(0, 10, 120, 25);

        jpwdSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpwdSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpwdSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jpwdSenha);
        jpwdSenha.setBounds(130, 10, 250, 25);

        jlblConfirmeSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblConfirmeSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblConfirmeSenha.setText("Confirme a Senha:");
        getContentPane().add(jlblConfirmeSenha);
        jlblConfirmeSenha.setBounds(0, 40, 120, 25);

        jpwdConfirmeSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpwdConfirmeSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpwdConfirmeSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jpwdConfirmeSenha);
        jpwdConfirmeSenha.setBounds(130, 40, 250, 25);

        jsepRodape.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(jsepRodape);
        jsepRodape.setBounds(10, 80, 380, 2);

        jbtnAlterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/password.png"))); // NOI18N
        jbtnAlterar.setText("Alterar");
        jbtnAlterar.setIconTextGap(10);
        jbtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlterarActionPerformed(evt);
            }
        });
        jbtnAlterar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnAlterarKeyPressed(evt);
            }
        });
        getContentPane().add(jbtnAlterar);
        jbtnAlterar.setBounds(140, 90, 120, 30);

        jbtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/cancel.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setIconTextGap(10);
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        jbtnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCancelarKeyPressed(evt);
            }
        });
        getContentPane().add(jbtnCancelar);
        jbtnCancelar.setBounds(270, 90, 120, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlterarActionPerformed
        
        trocarSenha();
        
    }//GEN-LAST:event_jbtnAlterarActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        
        fechar();
        
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jpwdSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwdSenhaKeyPressed
        
        atalho(evt);
        
    }//GEN-LAST:event_jpwdSenhaKeyPressed

    private void jpwdConfirmeSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwdConfirmeSenhaKeyPressed
        
        atalho(evt);
        
    }//GEN-LAST:event_jpwdConfirmeSenhaKeyPressed

    private void jbtnAlterarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnAlterarKeyPressed
        
        atalho(evt);
        
    }//GEN-LAST:event_jbtnAlterarKeyPressed

    private void jbtnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCancelarKeyPressed
        
        atalho(evt);
        
    }//GEN-LAST:event_jbtnCancelarKeyPressed

    private void trocarSenha() {
        
        try {
            
            String senha = new java.lang.String(jpwdSenha.getPassword()).trim();
            String confSenha = new java.lang.String(jpwdConfirmeSenha.getPassword()).trim();
            
            if (! senha.isEmpty() && ! confSenha.isEmpty()) {
                
                if (senha.equals(confSenha)) {
                    
                    java.lang.Object[] options = {"Sim", "Não"};
                    java.lang.Object opcao = javax.swing.JOptionPane.showOptionDialog(this, "Deseja realmente alterar a senha do usuário \"" + username + "\" no sistema?", "CadHab",
                            javax.swing.JOptionPane.DEFAULT_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null,
                            options, options[1]);

                    if (opcao.toString().equals("0")) {
                            
                        com.access.Usuario user = new com.access.Usuario();
                        user.setUsuario(username);
                        user.setSenha(senha);
                        
                        com.util.JsonManager jsonMgr = new com.util.JsonManager();
                        String input = jsonMgr.parseJson(user);
                    
                        java.lang.Object output = cadhab.conn.ConnectionManager.connect("/usuario/senha/atualizar?auth_token=" + cadhab.CadHab.usuario.getToken() + "&auth_key=" + cadhab.CadHab.usuario.getUserKey(), input);
                        
                        if (output != null) {
                            
                            if (output instanceof com.sys.Message) {
                                
                                com.sys.Message mensagem = (com.sys.Message) output;
                                javax.swing.JOptionPane.showMessageDialog(this, mensagem.getMessage(), "CadHab", mensagem.getCode());
                                this.dispose();
                                
                            }
                            
                        } else {
                            
                            javax.swing.JOptionPane.showMessageDialog(this, "Não foi possível alterar a senha do usuário \"" + username + "\"!", "CadHab", 0);
                            
                        }
                            
                    }
                    
                } else {
                    
                    javax.swing.JOptionPane.showMessageDialog(this, "A senha e a confirmação da senha são diferentes!", "CadHab", 2);
                    
                }
                
            } else {
                
                javax.swing.JOptionPane.showMessageDialog(this, "Você precisa informar a nova senha e confirmá-la!", "CadHab", 2);
                
            }
            
        } catch (java.net.MalformedURLException ex) {
            
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Não foi possível encontrar um caminho até o servidor!Verifique se as configurações do servidor estão corretas.", "CadHab", 0);
            
        } catch (java.net.ConnectException ex) {
            
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "O servidor do CadHab está temporariamente fora do ar!\nTente novamente mais tarde.", "CadHab", 0);
            
        } catch (java.io.IOException ex) {
            
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Não foi possível enviar/obter as informações para/do servidor!", "CadHab", 0);
            
        } catch (java.lang.Exception ex) {
            
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "CadHab", 0);
            
        }
        
    }
    
    private void fechar() {
        
        this.dispose();
        
    }
    
    private void atalho(java.awt.event.KeyEvent evt) {
        
        switch (evt.getKeyChar()) {
            
            case java.awt.event.KeyEvent.VK_ENTER: trocarSenha();
                break;
            case java.awt.event.KeyEvent.VK_ESCAPE: fechar();
                break;
            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAlterar;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JLabel jlblConfirmeSenha;
    private javax.swing.JLabel jlblSenha;
    private javax.swing.JPasswordField jpwdConfirmeSenha;
    private javax.swing.JPasswordField jpwdSenha;
    private javax.swing.JSeparator jsepRodape;
    // End of variables declaration//GEN-END:variables
}
