/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormGerenciarAreaRisco extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGerenciarAreaRisco
     */
    public FormGerenciarAreaRisco() {
        
        initComponents();
        
        try {
            
            com.sys.SystemSettings.setSystemThemeNimbus();
            
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscpPrincipal = new javax.swing.JScrollPane();
        jtbpPrincipal = new javax.swing.JTabbedPane();
        jpnlPesquisa = new javax.swing.JPanel();
        jpnlAreaRisco = new javax.swing.JPanel();
        jpnlAreaRiscoWrapper = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("CadHab - Gerenciamento de Áreas de Risco");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/hazard.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(700, 495));
        setMinimumSize(new java.awt.Dimension(0, 0));

        jscpPrincipal.setAutoscrolls(true);
        jscpPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtbpPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPesquisa.setLayout(null);
        jtbpPrincipal.addTab("Pesquisa", jpnlPesquisa);

        jpnlAreaRisco.setLayout(null);

        jpnlAreaRiscoWrapper.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Grau de Risco:");
        jpnlAreaRiscoWrapper.add(jLabel1);
        jLabel1.setBounds(10, 40, 110, 25);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlAreaRiscoWrapper.add(jTextField1);
        jTextField1.setBounds(180, 10, 120, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Código do Setor:");
        jpnlAreaRiscoWrapper.add(jLabel2);
        jLabel2.setBounds(10, 10, 110, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpnlAreaRiscoWrapper.add(jComboBox1);
        jComboBox1.setBounds(180, 40, 370, 25);

        jpnlAreaRisco.add(jpnlAreaRiscoWrapper);
        jpnlAreaRiscoWrapper.setBounds(0, 0, 680, 380);

        jtbpPrincipal.addTab("Área de Risco", jpnlAreaRisco);

        jscpPrincipal.setViewportView(jtbpPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jpnlAreaRisco;
    private javax.swing.JPanel jpnlAreaRiscoWrapper;
    private javax.swing.JPanel jpnlPesquisa;
    private javax.swing.JScrollPane jscpPrincipal;
    private javax.swing.JTabbedPane jtbpPrincipal;
    // End of variables declaration//GEN-END:variables
}
