/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormFerramentaConfigurarServidor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormFerramentaConfigurarServidor
     */
    public FormFerramentaConfigurarServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtngServidor = new javax.swing.ButtonGroup();
        jpnlPrincipal = new javax.swing.JPanel();
        jlblServidor = new javax.swing.JLabel();
        jrdbLocal = new javax.swing.JRadioButton();
        jrdbRemoto = new javax.swing.JRadioButton();
        jtxtServidor = new javax.swing.JTextField();
        jlblPorta = new javax.swing.JLabel();
        jtxtPorta = new javax.swing.JTextField();
        jlblProtocolo = new javax.swing.JLabel();
        jcbbProtocolo = new javax.swing.JComboBox();
        jsepRodape = new javax.swing.JSeparator();
        jbtnSalvar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("CadHab - Configurações do Servidor");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/serveredit.png"))); // NOI18N

        jpnlPrincipal.setLayout(null);

        jlblServidor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblServidor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblServidor.setText("Servidor:");
        jlblServidor.setToolTipText("Servidor do CadHab");
        jpnlPrincipal.add(jlblServidor);
        jlblServidor.setBounds(10, 10, 70, 25);

        jbtngServidor.add(jrdbLocal);
        jrdbLocal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrdbLocal.setSelected(true);
        jrdbLocal.setText("Local");
        jrdbLocal.setToolTipText("O Servidor Está Instalado Neste Computador");
        jrdbLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdbLocalActionPerformed(evt);
            }
        });
        jpnlPrincipal.add(jrdbLocal);
        jrdbLocal.setBounds(90, 10, 80, 23);

        jbtngServidor.add(jrdbRemoto);
        jrdbRemoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jrdbRemoto.setText("Remoto");
        jrdbRemoto.setToolTipText("O Servidor Está Instalado em Outro Computador");
        jrdbRemoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdbRemotoActionPerformed(evt);
            }
        });
        jpnlPrincipal.add(jrdbRemoto);
        jrdbRemoto.setBounds(190, 10, 100, 23);

        jtxtServidor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtServidor.setText("localhost");
        jtxtServidor.setEnabled(false);
        jpnlPrincipal.add(jtxtServidor);
        jtxtServidor.setBounds(90, 40, 290, 25);

        jlblPorta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPorta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblPorta.setText("Porta:");
        jlblPorta.setToolTipText("Porta de Conexão Com o Servidor");
        jpnlPrincipal.add(jlblPorta);
        jlblPorta.setBounds(10, 70, 70, 25);

        jtxtPorta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtPorta);
        jtxtPorta.setBounds(90, 70, 290, 25);

        jlblProtocolo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblProtocolo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblProtocolo.setText("Protocolo:");
        jlblProtocolo.setToolTipText("Protocolo de Comunicação entre a Aplicação e o Servidor");
        jpnlPrincipal.add(jlblProtocolo);
        jlblProtocolo.setBounds(10, 100, 70, 25);

        jcbbProtocolo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbProtocolo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "http", "https" }));
        jpnlPrincipal.add(jcbbProtocolo);
        jcbbProtocolo.setBounds(90, 100, 290, 25);
        jpnlPrincipal.add(jsepRodape);
        jsepRodape.setBounds(10, 140, 370, 2);

        jbtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/save.png"))); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setToolTipText("Salvar Dados");
        jbtnSalvar.setIconTextGap(10);
        jpnlPrincipal.add(jbtnSalvar);
        jbtnSalvar.setBounds(130, 150, 120, 30);

        jbtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/cancel.png"))); // NOI18N
        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.setToolTipText("Fechar Esta Janela");
        jbtnCancelar.setIconTextGap(10);
        jpnlPrincipal.add(jbtnCancelar);
        jbtnCancelar.setBounds(260, 150, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrdbRemotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbRemotoActionPerformed
        
        jtxtServidor.setText("");
        jtxtServidor.setEnabled(true);
        
    }//GEN-LAST:event_jrdbRemotoActionPerformed

    private void jrdbLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbLocalActionPerformed
        
        jtxtServidor.setText("localhost");
        jtxtServidor.setEnabled(false);
        
    }//GEN-LAST:event_jrdbLocalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.ButtonGroup jbtngServidor;
    private javax.swing.JComboBox jcbbProtocolo;
    private javax.swing.JLabel jlblPorta;
    private javax.swing.JLabel jlblProtocolo;
    private javax.swing.JLabel jlblServidor;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JRadioButton jrdbLocal;
    private javax.swing.JRadioButton jrdbRemoto;
    private javax.swing.JSeparator jsepRodape;
    private javax.swing.JTextField jtxtPorta;
    private javax.swing.JTextField jtxtServidor;
    // End of variables declaration//GEN-END:variables
}
