/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormGerenciarGrupo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGerenciarGrupo
     */
    public FormGerenciarGrupo() {
        
        initComponents();
        
        try {
            
            com.sys.SystemSettings.setSystemThemeNimbus();
            
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbpPrincipal = new javax.swing.JTabbedPane();
        jpnlPesquisa = new javax.swing.JPanel();
        jpnlPesquisar = new javax.swing.JPanel();
        jlblPesquisa = new javax.swing.JLabel();
        jtxtPesquisa = new javax.swing.JTextField();
        jlblFiltro = new javax.swing.JLabel();
        jcbbFiltro = new javax.swing.JComboBox();
        jbtnPesquisar = new javax.swing.JButton();
        jscpTabelaPesquisa = new javax.swing.JScrollPane();
        jtblPesquisa = new javax.swing.JTable();
        jpnlFormulario = new javax.swing.JPanel();
        jlblNome = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jlblDescricao = new javax.swing.JLabel();
        jpnlTextAreaDescricao = new javax.swing.JPanel();
        jscpTextAreaDescricao = new javax.swing.JScrollPane();
        jtxtaDescricao = new javax.swing.JTextArea();
        jpnlPermissoes = new javax.swing.JPanel();
        jtbpPermissoes = new javax.swing.JTabbedPane();
        jpnlRecursosAcesso = new javax.swing.JPanel();
        jckbGruposUsuarios = new javax.swing.JCheckBox();
        jckbUsuarios = new javax.swing.JCheckBox();
        jckbDepartamentos = new javax.swing.JCheckBox();
        jckbRecursosAcesso = new javax.swing.JCheckBox();
        jckbRecursosSociais = new javax.swing.JCheckBox();
        jbtnNovo = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnLimpar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CadHab - Gerenciamento de Grupos de Usuário");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/group.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));

        jtbpPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlPesquisar.setLayout(null);

        jlblPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPesquisa.setText("Pesquisa:");
        jpnlPesquisar.add(jlblPesquisa);
        jlblPesquisa.setBounds(0, 10, 70, 25);

        jtxtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPesquisar.add(jtxtPesquisa);
        jtxtPesquisa.setBounds(70, 10, 300, 25);

        jlblFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblFiltro.setText("Filtrar Por:");
        jpnlPesquisar.add(jlblFiltro);
        jlblFiltro.setBounds(380, 10, 70, 25);

        jcbbFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sem filtro" }));
        jpnlPesquisar.add(jcbbFiltro);
        jcbbFiltro.setBounds(450, 10, 180, 25);

        jbtnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/search.png"))); // NOI18N
        jbtnPesquisar.setText("Pesquisar");
        jbtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesquisarActionPerformed(evt);
            }
        });
        jpnlPesquisar.add(jbtnPesquisar);
        jbtnPesquisar.setBounds(640, 10, 120, 30);

        jtblPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Nome", "Descrição", "Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblPesquisa.getTableHeader().setReorderingAllowed(false);
        jscpTabelaPesquisa.setViewportView(jtblPesquisa);

        javax.swing.GroupLayout jpnlPesquisaLayout = new javax.swing.GroupLayout(jpnlPesquisa);
        jpnlPesquisa.setLayout(jpnlPesquisaLayout);
        jpnlPesquisaLayout.setHorizontalGroup(
            jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscpTabelaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnlPesquisaLayout.setVerticalGroup(
            jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpTabelaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbpPrincipal.addTab("Pesquisa", jpnlPesquisa);

        jpnlFormulario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlFormulario.setLayout(null);

        jlblNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNome.setText("Nome:");
        jpnlFormulario.add(jlblNome);
        jlblNome.setBounds(10, 10, 70, 25);

        jtxtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlFormulario.add(jtxtNome);
        jtxtNome.setBounds(90, 10, 680, 25);

        jlblDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDescricao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblDescricao.setText("Descrição:");
        jpnlFormulario.add(jlblDescricao);
        jlblDescricao.setBounds(10, 40, 70, 25);

        jtxtaDescricao.setColumns(20);
        jtxtaDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtaDescricao.setRows(5);
        jscpTextAreaDescricao.setViewportView(jtxtaDescricao);

        javax.swing.GroupLayout jpnlTextAreaDescricaoLayout = new javax.swing.GroupLayout(jpnlTextAreaDescricao);
        jpnlTextAreaDescricao.setLayout(jpnlTextAreaDescricaoLayout);
        jpnlTextAreaDescricaoLayout.setHorizontalGroup(
            jpnlTextAreaDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jpnlTextAreaDescricaoLayout.setVerticalGroup(
            jpnlTextAreaDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jpnlFormulario.add(jpnlTextAreaDescricao);
        jpnlTextAreaDescricao.setBounds(90, 40, 680, 100);

        jpnlPermissoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Permissões"));
        jpnlPermissoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtbpPermissoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlRecursosAcesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlRecursosAcesso.setLayout(null);

        jckbGruposUsuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbGruposUsuarios.setText("Grupos de Usuários");
        jckbGruposUsuarios.setToolTipText("É Portador de Síndrome de Down");
        jpnlRecursosAcesso.add(jckbGruposUsuarios);
        jckbGruposUsuarios.setBounds(10, 10, 180, 25);

        jckbUsuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbUsuarios.setText("Usuários");
        jckbUsuarios.setToolTipText("É Portador de Síndrome de Down");
        jpnlRecursosAcesso.add(jckbUsuarios);
        jckbUsuarios.setBounds(10, 40, 180, 25);

        jckbDepartamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbDepartamentos.setText("Secretarias");
        jckbDepartamentos.setToolTipText("É Portador de Síndrome de Down");
        jpnlRecursosAcesso.add(jckbDepartamentos);
        jckbDepartamentos.setBounds(10, 70, 180, 25);

        jckbRecursosAcesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbRecursosAcesso.setText("Recursos de Acesso");
        jckbRecursosAcesso.setToolTipText("É Portador de Síndrome de Down");
        jpnlRecursosAcesso.add(jckbRecursosAcesso);
        jckbRecursosAcesso.setBounds(10, 100, 180, 25);

        jckbRecursosSociais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbRecursosSociais.setText("Recursos Sociais");
        jckbRecursosSociais.setToolTipText("É Portador de Síndrome de Down");
        jpnlRecursosAcesso.add(jckbRecursosSociais);
        jckbRecursosSociais.setBounds(10, 130, 180, 25);

        jtbpPermissoes.addTab("Tipos de Permissões", jpnlRecursosAcesso);

        javax.swing.GroupLayout jpnlPermissoesLayout = new javax.swing.GroupLayout(jpnlPermissoes);
        jpnlPermissoes.setLayout(jpnlPermissoesLayout);
        jpnlPermissoesLayout.setHorizontalGroup(
            jpnlPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpPermissoes, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        jpnlPermissoesLayout.setVerticalGroup(
            jpnlPermissoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpPermissoes, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
        );

        jpnlFormulario.add(jpnlPermissoes);
        jpnlPermissoes.setBounds(10, 150, 760, 340);

        jbtnNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/new.png"))); // NOI18N
        jbtnNovo.setText("Novo");
        jbtnNovo.setIconTextGap(10);
        jbtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNovoActionPerformed(evt);
            }
        });
        jpnlFormulario.add(jbtnNovo);
        jbtnNovo.setBounds(130, 500, 120, 30);

        jbtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/save.png"))); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setIconTextGap(10);
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });
        jpnlFormulario.add(jbtnSalvar);
        jbtnSalvar.setBounds(260, 500, 120, 30);

        jbtnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/edit.png"))); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.setIconTextGap(10);
        jbtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarActionPerformed(evt);
            }
        });
        jpnlFormulario.add(jbtnEditar);
        jbtnEditar.setBounds(390, 500, 120, 30);

        jbtnLimpar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/clear.png"))); // NOI18N
        jbtnLimpar.setText("Limpar");
        jbtnLimpar.setIconTextGap(10);
        jbtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimparActionPerformed(evt);
            }
        });
        jpnlFormulario.add(jbtnLimpar);
        jbtnLimpar.setBounds(520, 500, 120, 30);

        jbtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/delete.png"))); // NOI18N
        jbtnExcluir.setText("Excluir");
        jbtnExcluir.setIconTextGap(10);
        jbtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExcluirActionPerformed(evt);
            }
        });
        jpnlFormulario.add(jbtnExcluir);
        jbtnExcluir.setBounds(650, 500, 120, 30);

        jtbpPrincipal.addTab("Grupo", jpnlFormulario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnPesquisarActionPerformed

    private void jbtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnNovoActionPerformed

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnLimparActionPerformed

    private void jbtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnExcluirActionPerformed

    private void limparCampos() {
        
        jtxtNome.setText("");
        jtxtaDescricao.setText("");
        
    }
    
    private void selecionarPermissoes() {
        
        jckbGruposUsuarios.setSelected(true);
        jckbUsuarios.setSelected(true);
        jckbDepartamentos.setSelected(true);
        jckbRecursosAcesso.setSelected(true);
        jckbRecursosSociais.setSelected(true);
        
    }
    
    private void deselecionarPermissoes() {
        
        jckbGruposUsuarios.setSelected(false);
        jckbUsuarios.setSelected(false);
        jckbDepartamentos.setSelected(false);
        jckbRecursosAcesso.setSelected(false);
        jckbRecursosSociais.setSelected(false);
        
    }
    
    private void habilitarCampos() {
        
        jtxtNome.setEnabled(true);
        jtxtaDescricao.setEnabled(true);
        jckbGruposUsuarios.setEnabled(true);
        jckbUsuarios.setEnabled(true);
        jckbDepartamentos.setEnabled(true);
        jckbRecursosAcesso.setEnabled(true);
        jckbRecursosSociais.setEnabled(true);
        
    }
    
    private void desabilitarCampos() {
        
        jtxtNome.setEnabled(false);
        jtxtaDescricao.setEnabled(false);
        jckbGruposUsuarios.setEnabled(false);
        jckbUsuarios.setEnabled(false);
        jckbDepartamentos.setEnabled(false);
        jckbRecursosAcesso.setEnabled(false);
        jckbRecursosSociais.setEnabled(false);
        
    }
    
    private void habilitarBotoes() {
        
        jbtnNovo.setEnabled(true);
        jbtnSalvar.setEnabled(true);
        jbtnEditar.setEnabled(true);
        jbtnLimpar.setEnabled(true);
        jbtnExcluir.setEnabled(true);
        
    }
    
    private void desabilitarBotoes() {
        
        jbtnNovo.setEnabled(false);
        jbtnSalvar.setEnabled(false);
        jbtnEditar.setEnabled(false);
        jbtnLimpar.setEnabled(false);
        jbtnExcluir.setEnabled(false);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnLimpar;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnPesquisar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox jcbbFiltro;
    private javax.swing.JCheckBox jckbDepartamentos;
    private javax.swing.JCheckBox jckbGruposUsuarios;
    private javax.swing.JCheckBox jckbRecursosAcesso;
    private javax.swing.JCheckBox jckbRecursosSociais;
    private javax.swing.JCheckBox jckbUsuarios;
    private javax.swing.JLabel jlblDescricao;
    private javax.swing.JLabel jlblFiltro;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblPesquisa;
    private javax.swing.JPanel jpnlFormulario;
    private javax.swing.JPanel jpnlPermissoes;
    private javax.swing.JPanel jpnlPesquisa;
    private javax.swing.JPanel jpnlPesquisar;
    private javax.swing.JPanel jpnlRecursosAcesso;
    private javax.swing.JPanel jpnlTextAreaDescricao;
    private javax.swing.JScrollPane jscpTabelaPesquisa;
    private javax.swing.JScrollPane jscpTextAreaDescricao;
    private javax.swing.JTable jtblPesquisa;
    private javax.swing.JTabbedPane jtbpPermissoes;
    private javax.swing.JTabbedPane jtbpPrincipal;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtPesquisa;
    private javax.swing.JTextArea jtxtaDescricao;
    // End of variables declaration//GEN-END:variables
}
