/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormGerenciarIndividuo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGerenciarIndividuo
     */
    public FormGerenciarIndividuo() {
        
        initComponents();
        
        try {
            
            com.sys.SystemSettings.setSystemThemeNimbus();
            
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtgDeficienciaVisual = new javax.swing.ButtonGroup();
        jbtgDeficienciaAuditiva = new javax.swing.ButtonGroup();
        jtbpPrincipal = new javax.swing.JTabbedPane();
        jpnlPesquisa = new javax.swing.JPanel();
        jscpTabelaPesquisa = new javax.swing.JScrollPane();
        jtblPesquisa = new javax.swing.JTable();
        jpnlPesquisar = new javax.swing.JPanel();
        jlblPesquisa = new javax.swing.JLabel();
        jtxtPesquisa = new javax.swing.JTextField();
        jlblFiltro = new javax.swing.JLabel();
        jcbbFiltro = new javax.swing.JComboBox();
        jbtnPesquisar = new javax.swing.JButton();
        jpnlFormulario = new javax.swing.JPanel();
        jtbpFormulario = new javax.swing.JTabbedPane();
        jpnlDadosIndividuo = new javax.swing.JPanel();
        jpnlDadosIndividuoWrapper = new javax.swing.JPanel();
        jlblFamilia = new javax.swing.JLabel();
        jcbbFamilia = new javax.swing.JComboBox();
        jlblResponsavelFamilia = new javax.swing.JLabel();
        jcbbResponsavelFamilia = new javax.swing.JComboBox();
        jlblGrauParentesco = new javax.swing.JLabel();
        jcbbGrauParentesco = new javax.swing.JComboBox();
        jlblNome = new javax.swing.JLabel();
        jtxtNome = new javax.swing.JTextField();
        jlblApelido = new javax.swing.JLabel();
        jtxtApelido = new javax.swing.JTextField();
        jlblSexo = new javax.swing.JLabel();
        jcbbSexo = new javax.swing.JComboBox();
        jlblEstadoCivil = new javax.swing.JLabel();
        jcbbEstadoCivil = new javax.swing.JComboBox();
        jlblEtinia = new javax.swing.JLabel();
        jcbbEtinia = new javax.swing.JComboBox();
        jlblIdade = new javax.swing.JLabel();
        jtxtIdade = new javax.swing.JTextField();
        jlblNomeMae = new javax.swing.JLabel();
        jtxtNomeMae = new javax.swing.JTextField();
        jlblNomePai = new javax.swing.JLabel();
        jtxtNomePai = new javax.swing.JTextField();
        jlblResponsavel = new javax.swing.JLabel();
        jtxtResponsavel = new javax.swing.JTextField();
        jlblPrestouInformacao = new javax.swing.JLabel();
        jtxtPrestouInformacao = new javax.swing.JTextField();
        jlblCpfInformante = new javax.swing.JLabel();
        jtxtCpfInformante = new javax.swing.JFormattedTextField();
        jpnlTextAreaObsIndividuo = new javax.swing.JPanel();
        jscpTextAreaObsIndividuo = new javax.swing.JScrollPane();
        jtxtaObsIndividuo = new javax.swing.JTextArea();
        jpnlListaTelefones = new javax.swing.JPanel();
        jscpListaTelefones = new javax.swing.JScrollPane();
        jlstTelefones = new javax.swing.JList();
        jbtnGerenciarTelefones = new javax.swing.JButton();
        jlblAnexos = new javax.swing.JLabel();
        jtxtAnexos = new javax.swing.JTextField();
        jbtnAnexos = new javax.swing.JButton();
        jpnlDocumentosCertidao = new javax.swing.JPanel();
        jpnlDocumentosCertidaoWrapper = new javax.swing.JPanel();
        jpnlCertidao = new javax.swing.JPanel();
        jlblDataNascimento = new javax.swing.JLabel();
        jtxtDataNascimento = new javax.swing.JFormattedTextField();
        jlblOndeNasceu = new javax.swing.JLabel();
        jtxtOndeNasceu = new javax.swing.JTextField();
        jlblNaturalidade = new javax.swing.JLabel();
        jtxtNaturalidade = new javax.swing.JTextField();
        jlblDataRegistro = new javax.swing.JLabel();
        jtxtDataRegistro = new javax.swing.JFormattedTextField();
        jlblNascimentoRegistrado = new javax.swing.JLabel();
        jcbbNascimentoRegistrado = new javax.swing.JComboBox();
        jlblNomeCartorio = new javax.swing.JLabel();
        jtxtNomeCartorio = new javax.swing.JTextField();
        jlblCodigoCartorio = new javax.swing.JLabel();
        jtxtCodigoCartorio = new javax.swing.JTextField();
        jlblTipoCertidao = new javax.swing.JLabel();
        jcbbTipoCertidao = new javax.swing.JComboBox();
        jlblUfCertidao = new javax.swing.JLabel();
        jcbbUfCertidao = new javax.swing.JComboBox();
        jlblMunicipioCertidao = new javax.swing.JLabel();
        jcbbMunicipioCertidao = new javax.swing.JComboBox();
        jlblNumeroTermo = new javax.swing.JLabel();
        jtxtNumeroTermo = new javax.swing.JTextField();
        jlblNumeroLivro = new javax.swing.JLabel();
        jtxtNumeroLivro = new javax.swing.JTextField();
        jlblNumeroFolha = new javax.swing.JLabel();
        jtxtNumeroFolha = new javax.swing.JTextField();
        jpnlTabelaDocumentos = new javax.swing.JPanel();
        jscpTabelaDocumentos = new javax.swing.JScrollPane();
        jtblDocumentos = new javax.swing.JTable();
        jbtnGerenciarDocumentos = new javax.swing.JButton();
        jpnlEscolaridadeProfissional = new javax.swing.JPanel();
        jpnlEscolaridadeProfissionalWrapper = new javax.swing.JPanel();
        jpnlDadosEscolares = new javax.swing.JPanel();
        jlblLeEscreve = new javax.swing.JLabel();
        jcbbLeEscreve = new javax.swing.JComboBox();
        jlblGrauEscolaridade = new javax.swing.JLabel();
        jcbbGrauEscolaridade = new javax.swing.JComboBox();
        jlblUnidadeEducacional = new javax.swing.JLabel();
        jtxtUnidadeEducacional = new javax.swing.JTextField();
        jpnlDadosProfissionais = new javax.swing.JPanel();
        jlblSituacaoProfissional = new javax.swing.JLabel();
        jcbbSituacaoProfissional = new javax.swing.JComboBox();
        jlblObsSituacao = new javax.swing.JLabel();
        jpnlTextAreaObsSituacao = new javax.swing.JPanel();
        jscpTextAreaObsSituacao = new javax.swing.JScrollPane();
        jtxtaObsSituacao = new javax.swing.JTextArea();
        jlblTipoTrabalho = new javax.swing.JLabel();
        jtxtTipoTrabalho = new javax.swing.JTextField();
        jlblObsTipo = new javax.swing.JLabel();
        jpnlTextAreaObsTipo = new javax.swing.JPanel();
        jscpTextAreaObsTipo = new javax.swing.JScrollPane();
        jtxtaObsTipo = new javax.swing.JTextArea();
        jlblNomeTrabalho = new javax.swing.JLabel();
        jtxtNomeTrabalho = new javax.swing.JTextField();
        jlblPossuiRenda = new javax.swing.JLabel();
        jcbbPossuiRenda = new javax.swing.JComboBox();
        jlblRenda = new javax.swing.JLabel();
        jtxtRenda = new javax.swing.JTextField();
        jlblDoacaoRegular = new javax.swing.JLabel();
        jtxtDoacaoRegular = new javax.swing.JTextField();
        jlblAposentadoriaPensao = new javax.swing.JLabel();
        jtxtAposentadoriaPensao = new javax.swing.JTextField();
        jlblSeguroDesemprego = new javax.swing.JLabel();
        jtxtSeguroDesemprego = new javax.swing.JTextField();
        jlblPensaoAlimentar = new javax.swing.JLabel();
        jtxtPensaoAlimentar = new javax.swing.JTextField();
        jlblOutrosBeneficios = new javax.swing.JLabel();
        jtxtOutrosBeneficios = new javax.swing.JTextField();
        jlblNumeroBpcloas = new javax.swing.JLabel();
        jtxtNumeroBpcloas = new javax.swing.JTextField();
        jpnlDeficiencia = new javax.swing.JPanel();
        jpnlDeficienciaWrapper = new javax.swing.JPanel();
        jlblDeficiente = new javax.swing.JLabel();
        jcbbDeficiente = new javax.swing.JComboBox();
        jpnlTipoDeficiencia = new javax.swing.JPanel();
        jckbCegueira = new javax.swing.JCheckBox();
        jckbBaixaVisao = new javax.swing.JCheckBox();
        jckbDeficienciaFisica = new javax.swing.JCheckBox();
        jckbSindromeDown = new javax.swing.JCheckBox();
        jckbSurdezSevera = new javax.swing.JCheckBox();
        jckbSurdezLeve = new javax.swing.JCheckBox();
        jckbDeficienciaMental = new javax.swing.JCheckBox();
        jckbTranstornoMental = new javax.swing.JCheckBox();
        jlblObsTipoDeficiencia = new javax.swing.JLabel();
        jpnlTextAreaObsTipoDeficiencia = new javax.swing.JPanel();
        jscpTextAreaObsTipoDeficiencia = new javax.swing.JScrollPane();
        jtxtaObsTipoDeficiencia = new javax.swing.JTextArea();
        jlblCausaDeficiencia = new javax.swing.JLabel();
        jtxtCausaDeficiencia = new javax.swing.JTextField();
        jlblObsCausaDeficiencia = new javax.swing.JLabel();
        jpnlTextAreaObsCausaDeficiencia = new javax.swing.JPanel();
        jscpTextAreaObsCausaDeficiencia = new javax.swing.JScrollPane();
        jtxtaObsCausaDeficiencia = new javax.swing.JTextArea();
        jlblQuandoAdquiriu = new javax.swing.JLabel();
        jtxtQuandoAdquiriu = new javax.swing.JTextField();
        jpnlDependeCuidados = new javax.swing.JPanel();
        jckbNaoDepende = new javax.swing.JCheckBox();
        jckbSimAlguemFamilia = new javax.swing.JCheckBox();
        jckbSimCuidadorEspecializado = new javax.swing.JCheckBox();
        jckbSimVizinho = new javax.swing.JCheckBox();
        jckbSimInstituicao = new javax.swing.JCheckBox();
        jckbSimOutraForma = new javax.swing.JCheckBox();
        jlblCadastroSepedi = new javax.swing.JLabel();
        jcbbCadastroSepedi = new javax.swing.JComboBox();
        jpnlRodape = new javax.swing.JPanel();
        jpnlRodapeWrapper = new javax.swing.JPanel();
        jbtnNovo = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CadHab - Gerenciamento de Indivíduos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/subject.png"))); // NOI18N

        jtbpPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscpTabelaPesquisa.setViewportView(jtblPesquisa);

        jpnlPesquisar.setLayout(null);

        jlblPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPesquisa.setText("Pesquisa:");
        jpnlPesquisar.add(jlblPesquisa);
        jlblPesquisa.setBounds(0, 10, 70, 25);

        jtxtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPesquisar.add(jtxtPesquisa);
        jtxtPesquisa.setBounds(70, 10, 480, 25);

        jlblFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblFiltro.setText("Filtrar Por:");
        jpnlPesquisar.add(jlblFiltro);
        jlblFiltro.setBounds(570, 10, 70, 25);

        jcbbFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sem filtro" }));
        jpnlPesquisar.add(jcbbFiltro);
        jcbbFiltro.setBounds(640, 10, 200, 25);

        jbtnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/search.png"))); // NOI18N
        jbtnPesquisar.setText("Pesquisar");
        jpnlPesquisar.add(jbtnPesquisar);
        jbtnPesquisar.setBounds(850, 10, 120, 30);

        javax.swing.GroupLayout jpnlPesquisaLayout = new javax.swing.GroupLayout(jpnlPesquisa);
        jpnlPesquisa.setLayout(jpnlPesquisaLayout);
        jpnlPesquisaLayout.setHorizontalGroup(
            jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPesquisaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jpnlPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 17, Short.MAX_VALUE))
            .addGroup(jpnlPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpTabelaPesquisa)
                .addContainerGap())
        );
        jpnlPesquisaLayout.setVerticalGroup(
            jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPesquisaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jpnlPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpTabelaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbpPrincipal.addTab("Pesquisa", null, jpnlPesquisa, "Pesquisar Por Indivíduos Registrados no Sistema");

        jpnlFormulario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlFormulario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlFormularioComponentResized(evt);
            }
        });

        jtbpFormulario.setToolTipText("Dados de Deficiência do Indivíduo");
        jtbpFormulario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlDadosIndividuo.setToolTipText("");
        jpnlDadosIndividuo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlDadosIndividuoComponentResized(evt);
            }
        });
        jpnlDadosIndividuo.setLayout(null);

        jpnlDadosIndividuoWrapper.setToolTipText("");
        jpnlDadosIndividuoWrapper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.setLayout(null);

        jlblFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblFamilia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblFamilia.setText("Família:");
        jlblFamilia.setToolTipText("Família ao Qual o Indivíduo Pertence");
        jpnlDadosIndividuoWrapper.add(jlblFamilia);
        jlblFamilia.setBounds(10, 10, 120, 25);

        jcbbFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbFamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma família" }));
        jpnlDadosIndividuoWrapper.add(jcbbFamilia);
        jcbbFamilia.setBounds(140, 10, 340, 25);

        jlblResponsavelFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblResponsavelFamilia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblResponsavelFamilia.setText("Respons. Família:");
        jlblResponsavelFamilia.setToolTipText("É Responsável Pela Família?");
        jpnlDadosIndividuoWrapper.add(jlblResponsavelFamilia);
        jlblResponsavelFamilia.setBounds(10, 40, 120, 25);

        jcbbResponsavelFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbResponsavelFamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Sim", "Não" }));
        jpnlDadosIndividuoWrapper.add(jcbbResponsavelFamilia);
        jcbbResponsavelFamilia.setBounds(140, 40, 340, 25);

        jlblGrauParentesco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblGrauParentesco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblGrauParentesco.setText("Grau Parentesco:");
        jlblGrauParentesco.setToolTipText("Grau de Parentesco em Relação ao Responsável Pela Família");
        jpnlDadosIndividuoWrapper.add(jlblGrauParentesco);
        jlblGrauParentesco.setBounds(10, 70, 120, 25);

        jcbbGrauParentesco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbGrauParentesco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um parentesco", "Pai/Mãe", "Filho/Filha", "Irmão/Irmã", "Avô/Avó", "Neto/Neta", "Tio/Tia", "Primo/Prima", "Sobrinho/Sobrinha", "Cônjuge", "Genro/Nora", "Sogro/Sogra", "Cunhado/Cunhada", "Sem grau de parentesco" }));
        jpnlDadosIndividuoWrapper.add(jcbbGrauParentesco);
        jcbbGrauParentesco.setBounds(140, 70, 340, 25);

        jlblNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNome.setText("Nome:");
        jlblNome.setToolTipText("Nome do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblNome);
        jlblNome.setBounds(10, 100, 120, 25);

        jtxtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtNome);
        jtxtNome.setBounds(140, 100, 340, 25);

        jlblApelido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblApelido.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblApelido.setText("Apelido:");
        jlblApelido.setToolTipText("Apelido do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblApelido);
        jlblApelido.setBounds(10, 130, 120, 25);

        jtxtApelido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtApelido);
        jtxtApelido.setBounds(140, 130, 340, 25);

        jlblSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSexo.setText("Sexo:");
        jlblSexo.setToolTipText("Sexo do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblSexo);
        jlblSexo.setBounds(10, 160, 120, 25);

        jcbbSexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Masculino", "Feminino" }));
        jpnlDadosIndividuoWrapper.add(jcbbSexo);
        jcbbSexo.setBounds(140, 160, 340, 25);

        jlblEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblEstadoCivil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblEstadoCivil.setText("Estado Civil:");
        jlblEstadoCivil.setToolTipText("Estado Civil do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblEstadoCivil);
        jlblEstadoCivil.setBounds(10, 190, 120, 25);

        jcbbEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Solteiro(a)", "Amaziado(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)", "Outros" }));
        jpnlDadosIndividuoWrapper.add(jcbbEstadoCivil);
        jcbbEstadoCivil.setBounds(140, 190, 340, 25);

        jlblEtinia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblEtinia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblEtinia.setText("Etinia:");
        jlblEtinia.setToolTipText("Etinia do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblEtinia);
        jlblEtinia.setBounds(10, 220, 120, 25);

        jcbbEtinia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbEtinia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Branca", "Amarela", "Parda", "Indígena", "Negra" }));
        jpnlDadosIndividuoWrapper.add(jcbbEtinia);
        jcbbEtinia.setBounds(140, 220, 340, 25);

        jlblIdade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblIdade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblIdade.setText("Idade:");
        jlblIdade.setToolTipText("Idade do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblIdade);
        jlblIdade.setBounds(10, 250, 120, 25);

        jtxtIdade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtIdade);
        jtxtIdade.setBounds(140, 250, 340, 25);

        jlblNomeMae.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNomeMae.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNomeMae.setText("Nome Mãe:");
        jlblNomeMae.setToolTipText("Nome da Mãe do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblNomeMae);
        jlblNomeMae.setBounds(10, 280, 120, 25);

        jtxtNomeMae.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtNomeMae);
        jtxtNomeMae.setBounds(140, 280, 340, 25);

        jlblNomePai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNomePai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNomePai.setText("Nome Pai:");
        jlblNomePai.setToolTipText("Nome do Pai do Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblNomePai);
        jlblNomePai.setBounds(10, 310, 120, 25);

        jtxtNomePai.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtNomePai);
        jtxtNomePai.setBounds(140, 310, 340, 25);

        jlblResponsavel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblResponsavel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblResponsavel.setText("Responsável:");
        jlblResponsavel.setToolTipText("Responsável Pelo Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblResponsavel);
        jlblResponsavel.setBounds(10, 340, 120, 25);

        jtxtResponsavel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtResponsavel);
        jtxtResponsavel.setBounds(140, 340, 340, 25);

        jlblPrestouInformacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPrestouInformacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblPrestouInformacao.setText("Prestou Informação:");
        jlblPrestouInformacao.setToolTipText("Nome da Pessoa que Prestou as Informações Sobre o Indivíduo");
        jpnlDadosIndividuoWrapper.add(jlblPrestouInformacao);
        jlblPrestouInformacao.setBounds(10, 370, 120, 25);

        jtxtPrestouInformacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtPrestouInformacao);
        jtxtPrestouInformacao.setBounds(140, 370, 340, 25);

        jlblCpfInformante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblCpfInformante.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCpfInformante.setText("CPF Informante:");
        jlblCpfInformante.setToolTipText("Número de CPF da Pessoa que Prestou as Informações Sobre o Indivíduo (Quando Maior de 16 Anos de Idade)");
        jpnlDadosIndividuoWrapper.add(jlblCpfInformante);
        jlblCpfInformante.setBounds(10, 400, 120, 25);

        jtxtCpfInformante.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jtxtCpfInformante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtCpfInformante);
        jtxtCpfInformante.setBounds(140, 400, 340, 25);

        jpnlTextAreaObsIndividuo.setBorder(javax.swing.BorderFactory.createTitledBorder("Observações"));
        jpnlTextAreaObsIndividuo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtxtaObsIndividuo.setColumns(20);
        jtxtaObsIndividuo.setRows(5);
        jscpTextAreaObsIndividuo.setViewportView(jtxtaObsIndividuo);

        javax.swing.GroupLayout jpnlTextAreaObsIndividuoLayout = new javax.swing.GroupLayout(jpnlTextAreaObsIndividuo);
        jpnlTextAreaObsIndividuo.setLayout(jpnlTextAreaObsIndividuoLayout);
        jpnlTextAreaObsIndividuoLayout.setHorizontalGroup(
            jpnlTextAreaObsIndividuoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTextAreaObsIndividuoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpTextAreaObsIndividuo, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlTextAreaObsIndividuoLayout.setVerticalGroup(
            jpnlTextAreaObsIndividuoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTextAreaObsIndividuoLayout.createSequentialGroup()
                .addComponent(jscpTextAreaObsIndividuo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnlDadosIndividuoWrapper.add(jpnlTextAreaObsIndividuo);
        jpnlTextAreaObsIndividuo.setBounds(490, 10, 490, 210);

        jpnlListaTelefones.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefones"));
        jpnlListaTelefones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlstTelefones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlstTelefones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jscpListaTelefones.setViewportView(jlstTelefones);

        jbtnGerenciarTelefones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnGerenciarTelefones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/manage.png"))); // NOI18N
        jbtnGerenciarTelefones.setToolTipText("Gerenciar Telefones Pertencentes ao Indivíduo");

        javax.swing.GroupLayout jpnlListaTelefonesLayout = new javax.swing.GroupLayout(jpnlListaTelefones);
        jpnlListaTelefones.setLayout(jpnlListaTelefonesLayout);
        jpnlListaTelefonesLayout.setHorizontalGroup(
            jpnlListaTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlListaTelefonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpListaTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnGerenciarTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlListaTelefonesLayout.setVerticalGroup(
            jpnlListaTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlListaTelefonesLayout.createSequentialGroup()
                .addGroup(jpnlListaTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlListaTelefonesLayout.createSequentialGroup()
                        .addComponent(jbtnGerenciarTelefones)
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addComponent(jscpListaTelefones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jpnlDadosIndividuoWrapper.add(jpnlListaTelefones);
        jpnlListaTelefones.setBounds(490, 230, 490, 190);

        jlblAnexos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblAnexos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblAnexos.setText("Anexos:");
        jlblAnexos.setToolTipText("Documentos Anexos do Indivíduo (Imagens, Planilhas, Documentos de Texto, Etc.)");
        jpnlDadosIndividuoWrapper.add(jlblAnexos);
        jlblAnexos.setBounds(490, 430, 80, 25);

        jtxtAnexos.setEditable(false);
        jtxtAnexos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosIndividuoWrapper.add(jtxtAnexos);
        jtxtAnexos.setBounds(580, 430, 400, 25);

        jbtnAnexos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnAnexos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/attach.png"))); // NOI18N
        jbtnAnexos.setText("Anexos");
        jbtnAnexos.setToolTipText("Gerenciar Documentos Anexos do Indivíduo (Imagens, Planilhas, Documentos de Texto, Etc.)");
        jpnlDadosIndividuoWrapper.add(jbtnAnexos);
        jbtnAnexos.setBounds(860, 460, 120, 30);

        jpnlDadosIndividuo.add(jpnlDadosIndividuoWrapper);
        jpnlDadosIndividuoWrapper.setBounds(0, 0, 990, 500);

        jtbpFormulario.addTab("Dados do Indivíduo", null, jpnlDadosIndividuo, "Informações Pessoais do Indivíduo");

        jpnlDocumentosCertidao.setToolTipText("");
        jpnlDocumentosCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDocumentosCertidao.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlDocumentosCertidaoComponentResized(evt);
            }
        });
        jpnlDocumentosCertidao.setLayout(null);

        jpnlDocumentosCertidaoWrapper.setToolTipText("");
        jpnlDocumentosCertidaoWrapper.setLayout(null);

        jpnlCertidao.setBorder(javax.swing.BorderFactory.createTitledBorder("Certidão"));
        jpnlCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.setLayout(null);

        jlblDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDataNascimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblDataNascimento.setText("Data Nascimento:");
        jlblDataNascimento.setToolTipText("Data de Nascimento do Indivíduo");
        jpnlCertidao.add(jlblDataNascimento);
        jlblDataNascimento.setBounds(10, 20, 120, 25);

        jtxtDataNascimento.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jtxtDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtDataNascimento);
        jtxtDataNascimento.setBounds(140, 20, 340, 25);

        jlblOndeNasceu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblOndeNasceu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblOndeNasceu.setText("Onde Nasceu:");
        jlblOndeNasceu.setToolTipText("Local Onde o Indivíduo Nasceu");
        jpnlCertidao.add(jlblOndeNasceu);
        jlblOndeNasceu.setBounds(10, 50, 120, 25);

        jtxtOndeNasceu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtOndeNasceu);
        jtxtOndeNasceu.setBounds(140, 50, 340, 25);

        jlblNaturalidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNaturalidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNaturalidade.setText("Naturalidade:");
        jlblNaturalidade.setToolTipText("Naturalidade do Indivíduo");
        jpnlCertidao.add(jlblNaturalidade);
        jlblNaturalidade.setBounds(10, 80, 120, 25);

        jtxtNaturalidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtNaturalidade);
        jtxtNaturalidade.setBounds(140, 80, 340, 25);

        jlblDataRegistro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDataRegistro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblDataRegistro.setText("Data Registro:");
        jlblDataRegistro.setToolTipText("Data de Registro da Certidão do Indivíduo");
        jpnlCertidao.add(jlblDataRegistro);
        jlblDataRegistro.setBounds(10, 110, 120, 25);

        jtxtDataRegistro.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jtxtDataRegistro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtDataRegistro);
        jtxtDataRegistro.setBounds(140, 110, 340, 25);

        jlblNascimentoRegistrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNascimentoRegistrado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNascimentoRegistrado.setText("Nasc. Registrado:");
        jlblNascimentoRegistrado.setToolTipText("O Nascimento do Indivíduo Foi Registrado?");
        jpnlCertidao.add(jlblNascimentoRegistrado);
        jlblNascimentoRegistrado.setBounds(10, 140, 120, 25);

        jcbbNascimentoRegistrado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbNascimentoRegistrado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Sim", "Não" }));
        jpnlCertidao.add(jcbbNascimentoRegistrado);
        jcbbNascimentoRegistrado.setBounds(140, 140, 340, 25);

        jlblNomeCartorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNomeCartorio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNomeCartorio.setText("Nome Cartório:");
        jlblNomeCartorio.setToolTipText("Nome do Cartório Onde a Certidão Foi Registrada");
        jpnlCertidao.add(jlblNomeCartorio);
        jlblNomeCartorio.setBounds(10, 170, 120, 25);

        jtxtNomeCartorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtNomeCartorio);
        jtxtNomeCartorio.setBounds(140, 170, 340, 25);

        jlblCodigoCartorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblCodigoCartorio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCodigoCartorio.setText("Código Cartório:");
        jlblCodigoCartorio.setToolTipText("Código do Cartório Onde a Certidão Foi Registrada");
        jpnlCertidao.add(jlblCodigoCartorio);
        jlblCodigoCartorio.setBounds(10, 200, 120, 25);

        jtxtCodigoCartorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtCodigoCartorio);
        jtxtCodigoCartorio.setBounds(140, 200, 340, 25);

        jlblTipoCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblTipoCertidao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTipoCertidao.setText("Tipo Certidão:");
        jlblTipoCertidao.setToolTipText("Tipo da Certidão");
        jpnlCertidao.add(jlblTipoCertidao);
        jlblTipoCertidao.setBounds(490, 20, 120, 25);

        jcbbTipoCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbTipoCertidao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Nascimento", "Casamento" }));
        jpnlCertidao.add(jcbbTipoCertidao);
        jcbbTipoCertidao.setBounds(620, 20, 340, 25);

        jlblUfCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblUfCertidao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblUfCertidao.setText("UF Certidão:");
        jlblUfCertidao.setToolTipText("Estado da Certidão");
        jpnlCertidao.add(jlblUfCertidao);
        jlblUfCertidao.setBounds(490, 50, 120, 25);

        jcbbUfCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbUfCertidao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção" }));
        jpnlCertidao.add(jcbbUfCertidao);
        jcbbUfCertidao.setBounds(620, 50, 340, 25);

        jlblMunicipioCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblMunicipioCertidao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblMunicipioCertidao.setText("Município Certidão:");
        jlblMunicipioCertidao.setToolTipText("Município da Certidão");
        jpnlCertidao.add(jlblMunicipioCertidao);
        jlblMunicipioCertidao.setBounds(490, 80, 120, 25);

        jcbbMunicipioCertidao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbMunicipioCertidao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção" }));
        jpnlCertidao.add(jcbbMunicipioCertidao);
        jcbbMunicipioCertidao.setBounds(620, 80, 340, 25);

        jlblNumeroTermo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNumeroTermo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNumeroTermo.setText("Número Termo:");
        jlblNumeroTermo.setToolTipText("Número do Termo de Registro");
        jpnlCertidao.add(jlblNumeroTermo);
        jlblNumeroTermo.setBounds(490, 110, 120, 25);

        jtxtNumeroTermo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtNumeroTermo);
        jtxtNumeroTermo.setBounds(620, 110, 340, 25);

        jlblNumeroLivro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNumeroLivro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNumeroLivro.setText("Número Livro:");
        jlblNumeroLivro.setToolTipText("Número do Livro de Registro");
        jpnlCertidao.add(jlblNumeroLivro);
        jlblNumeroLivro.setBounds(490, 140, 120, 25);

        jtxtNumeroLivro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtNumeroLivro);
        jtxtNumeroLivro.setBounds(620, 140, 340, 25);

        jlblNumeroFolha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNumeroFolha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNumeroFolha.setText("Número Folha:");
        jlblNumeroFolha.setToolTipText("Número da Folha de Registro");
        jpnlCertidao.add(jlblNumeroFolha);
        jlblNumeroFolha.setBounds(490, 170, 120, 25);

        jtxtNumeroFolha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlCertidao.add(jtxtNumeroFolha);
        jtxtNumeroFolha.setBounds(620, 170, 340, 25);

        jpnlDocumentosCertidaoWrapper.add(jpnlCertidao);
        jpnlCertidao.setBounds(10, 10, 970, 240);

        jpnlTabelaDocumentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentos"));
        jpnlTabelaDocumentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtblDocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscpTabelaDocumentos.setViewportView(jtblDocumentos);

        jbtnGerenciarDocumentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnGerenciarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/manage.png"))); // NOI18N
        jbtnGerenciarDocumentos.setToolTipText("Gerenciar Documentos do Indivíduo");

        javax.swing.GroupLayout jpnlTabelaDocumentosLayout = new javax.swing.GroupLayout(jpnlTabelaDocumentos);
        jpnlTabelaDocumentos.setLayout(jpnlTabelaDocumentosLayout);
        jpnlTabelaDocumentosLayout.setHorizontalGroup(
            jpnlTabelaDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTabelaDocumentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpTabelaDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnGerenciarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlTabelaDocumentosLayout.setVerticalGroup(
            jpnlTabelaDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlTabelaDocumentosLayout.createSequentialGroup()
                .addGroup(jpnlTabelaDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscpTabelaDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpnlTabelaDocumentosLayout.createSequentialGroup()
                        .addComponent(jbtnGerenciarDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jpnlDocumentosCertidaoWrapper.add(jpnlTabelaDocumentos);
        jpnlTabelaDocumentos.setBounds(10, 260, 970, 230);

        jpnlDocumentosCertidao.add(jpnlDocumentosCertidaoWrapper);
        jpnlDocumentosCertidaoWrapper.setBounds(0, 0, 990, 500);

        jtbpFormulario.addTab("Documentos/Certidão", null, jpnlDocumentosCertidao, "Registro de Documentos e Certidões do Indivíduo");

        jpnlEscolaridadeProfissional.setToolTipText("");
        jpnlEscolaridadeProfissional.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlEscolaridadeProfissional.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlEscolaridadeProfissionalComponentResized(evt);
            }
        });
        jpnlEscolaridadeProfissional.setLayout(null);

        jpnlEscolaridadeProfissionalWrapper.setToolTipText("");
        jpnlEscolaridadeProfissionalWrapper.setLayout(null);

        jpnlDadosEscolares.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Escolares"));
        jpnlDadosEscolares.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEscolares.setLayout(null);

        jlblLeEscreve.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblLeEscreve.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblLeEscreve.setText("Lê/Escreve:");
        jlblLeEscreve.setToolTipText("O Indivíduo Lê e/ou Escreve?");
        jpnlDadosEscolares.add(jlblLeEscreve);
        jlblLeEscreve.setBounds(10, 20, 120, 25);

        jcbbLeEscreve.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbLeEscreve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Lê", "Escreve", "Lê e escreve" }));
        jpnlDadosEscolares.add(jcbbLeEscreve);
        jcbbLeEscreve.setBounds(140, 20, 340, 25);

        jlblGrauEscolaridade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblGrauEscolaridade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblGrauEscolaridade.setText("Grau Escolaridade:");
        jlblGrauEscolaridade.setToolTipText("Grau de Escolaridade do Indivíduo");
        jpnlDadosEscolares.add(jlblGrauEscolaridade);
        jlblGrauEscolaridade.setBounds(490, 20, 120, 25);

        jcbbGrauEscolaridade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbGrauEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Analfabeto", "Alfabetizado", "Ensino fundamental incompleto", "Ensino fundamental completo", "Ensino médio incompleto", "Ensino médio completo", "Superior incompleto", "Superior completo", "Pós-graduação incompleta", "Pós-graduação completa" }));
        jpnlDadosEscolares.add(jcbbGrauEscolaridade);
        jcbbGrauEscolaridade.setBounds(620, 20, 340, 25);

        jlblUnidadeEducacional.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblUnidadeEducacional.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblUnidadeEducacional.setText("Unid. Educacional:");
        jlblUnidadeEducacional.setToolTipText("Unidade Educacional do Indivíduo");
        jpnlDadosEscolares.add(jlblUnidadeEducacional);
        jlblUnidadeEducacional.setBounds(10, 50, 120, 25);

        jtxtUnidadeEducacional.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEscolares.add(jtxtUnidadeEducacional);
        jtxtUnidadeEducacional.setBounds(140, 50, 820, 25);

        jpnlEscolaridadeProfissionalWrapper.add(jpnlDadosEscolares);
        jpnlDadosEscolares.setBounds(10, 10, 970, 90);

        jpnlDadosProfissionais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Profissionais"));
        jpnlDadosProfissionais.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.setLayout(null);

        jlblSituacaoProfissional.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblSituacaoProfissional.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSituacaoProfissional.setText("Situação:");
        jlblSituacaoProfissional.setToolTipText("Situação Trabalhista do Indivíduo");
        jpnlDadosProfissionais.add(jlblSituacaoProfissional);
        jlblSituacaoProfissional.setBounds(10, 20, 120, 25);

        jcbbSituacaoProfissional.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbSituacaoProfissional.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Trabalhador por conta própria (bico, autônomo)", "Trabalhador temporário em área rural", "Empregado sem carteira de trabalho assinada", "Empregado com carteira de trabalho assinada", "Trabalhador doméstico sem carteira de trabalho assinada", "Trabalhador doméstico com carteira de trabalho assinada", "Trabalhador não-remunerado", "Militar ou servidor público", "Empregador", "Estagiário", "Aprendiz" }));
        jpnlDadosProfissionais.add(jcbbSituacaoProfissional);
        jcbbSituacaoProfissional.setBounds(140, 20, 340, 25);

        jlblObsSituacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblObsSituacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblObsSituacao.setText("Obs. Situação:");
        jlblObsSituacao.setToolTipText("Observações Referentes à Situação Trabalhista do Indivíduo");
        jpnlDadosProfissionais.add(jlblObsSituacao);
        jlblObsSituacao.setBounds(10, 50, 120, 25);

        jtxtaObsSituacao.setColumns(20);
        jtxtaObsSituacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtaObsSituacao.setRows(5);
        jscpTextAreaObsSituacao.setViewportView(jtxtaObsSituacao);

        javax.swing.GroupLayout jpnlTextAreaObsSituacaoLayout = new javax.swing.GroupLayout(jpnlTextAreaObsSituacao);
        jpnlTextAreaObsSituacao.setLayout(jpnlTextAreaObsSituacaoLayout);
        jpnlTextAreaObsSituacaoLayout.setHorizontalGroup(
            jpnlTextAreaObsSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jpnlTextAreaObsSituacaoLayout.setVerticalGroup(
            jpnlTextAreaObsSituacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsSituacao, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jpnlDadosProfissionais.add(jpnlTextAreaObsSituacao);
        jpnlTextAreaObsSituacao.setBounds(140, 50, 340, 150);

        jlblTipoTrabalho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblTipoTrabalho.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTipoTrabalho.setText("Tipo Trabalho:");
        jlblTipoTrabalho.setToolTipText("Tipo de Trabalho do Indivíduo");
        jpnlDadosProfissionais.add(jlblTipoTrabalho);
        jlblTipoTrabalho.setBounds(10, 205, 120, 25);

        jtxtTipoTrabalho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtTipoTrabalho);
        jtxtTipoTrabalho.setBounds(140, 205, 340, 25);

        jlblObsTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblObsTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblObsTipo.setText("Obs. Tipo:");
        jlblObsTipo.setToolTipText("Observações Referentes ao Tipo de Trabalho do Indivíduo");
        jpnlDadosProfissionais.add(jlblObsTipo);
        jlblObsTipo.setBounds(10, 235, 120, 25);

        jtxtaObsTipo.setColumns(20);
        jtxtaObsTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtaObsTipo.setRows(5);
        jscpTextAreaObsTipo.setViewportView(jtxtaObsTipo);

        javax.swing.GroupLayout jpnlTextAreaObsTipoLayout = new javax.swing.GroupLayout(jpnlTextAreaObsTipo);
        jpnlTextAreaObsTipo.setLayout(jpnlTextAreaObsTipoLayout);
        jpnlTextAreaObsTipoLayout.setHorizontalGroup(
            jpnlTextAreaObsTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jpnlTextAreaObsTipoLayout.setVerticalGroup(
            jpnlTextAreaObsTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jpnlDadosProfissionais.add(jpnlTextAreaObsTipo);
        jpnlTextAreaObsTipo.setBounds(140, 235, 340, 140);

        jlblNomeTrabalho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNomeTrabalho.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNomeTrabalho.setText("Nome Trabalho:");
        jlblNomeTrabalho.setToolTipText("Nome do Trabalho do Indivíduo");
        jpnlDadosProfissionais.add(jlblNomeTrabalho);
        jlblNomeTrabalho.setBounds(490, 20, 120, 25);

        jtxtNomeTrabalho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtNomeTrabalho);
        jtxtNomeTrabalho.setBounds(620, 20, 340, 25);

        jlblPossuiRenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPossuiRenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblPossuiRenda.setText("Possui Renda:");
        jlblPossuiRenda.setToolTipText("Possui Renda?");
        jpnlDadosProfissionais.add(jlblPossuiRenda);
        jlblPossuiRenda.setBounds(490, 50, 120, 25);

        jcbbPossuiRenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbPossuiRenda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Sim", "Não" }));
        jpnlDadosProfissionais.add(jcbbPossuiRenda);
        jcbbPossuiRenda.setBounds(620, 50, 340, 25);

        jlblRenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblRenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblRenda.setText("Renda:");
        jlblRenda.setToolTipText("Valor da Renda Mensal");
        jpnlDadosProfissionais.add(jlblRenda);
        jlblRenda.setBounds(490, 80, 120, 25);

        jtxtRenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtRenda);
        jtxtRenda.setBounds(620, 80, 340, 25);

        jlblDoacaoRegular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDoacaoRegular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblDoacaoRegular.setText("Doação Regular:");
        jlblDoacaoRegular.setToolTipText("Valor de Doação Regular Que Recebe");
        jpnlDadosProfissionais.add(jlblDoacaoRegular);
        jlblDoacaoRegular.setBounds(490, 110, 120, 25);

        jtxtDoacaoRegular.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtDoacaoRegular);
        jtxtDoacaoRegular.setBounds(620, 110, 340, 25);

        jlblAposentadoriaPensao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblAposentadoriaPensao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblAposentadoriaPensao.setText("Aposent./Pensão:");
        jlblAposentadoriaPensao.setToolTipText("Valor de Aposentadoria ou Pensão Que Recebe");
        jpnlDadosProfissionais.add(jlblAposentadoriaPensao);
        jlblAposentadoriaPensao.setBounds(490, 140, 120, 25);

        jtxtAposentadoriaPensao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtAposentadoriaPensao);
        jtxtAposentadoriaPensao.setBounds(620, 140, 340, 25);

        jlblSeguroDesemprego.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblSeguroDesemprego.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblSeguroDesemprego.setText("Seguro Desemp.:");
        jlblSeguroDesemprego.setToolTipText("Valor do Seguro desemprego Que Recebe");
        jpnlDadosProfissionais.add(jlblSeguroDesemprego);
        jlblSeguroDesemprego.setBounds(490, 170, 120, 25);

        jtxtSeguroDesemprego.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtSeguroDesemprego);
        jtxtSeguroDesemprego.setBounds(620, 170, 340, 25);

        jlblPensaoAlimentar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPensaoAlimentar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblPensaoAlimentar.setText("Pensão Alimentar:");
        jlblPensaoAlimentar.setToolTipText("Valor da Pensão Alimentícia Que Recebe");
        jpnlDadosProfissionais.add(jlblPensaoAlimentar);
        jlblPensaoAlimentar.setBounds(490, 200, 120, 25);

        jtxtPensaoAlimentar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtPensaoAlimentar);
        jtxtPensaoAlimentar.setBounds(620, 200, 340, 25);

        jlblOutrosBeneficios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblOutrosBeneficios.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblOutrosBeneficios.setText("Outros Benefícios:");
        jlblOutrosBeneficios.setToolTipText("Valor de Outros Benefícios Que Recebe");
        jpnlDadosProfissionais.add(jlblOutrosBeneficios);
        jlblOutrosBeneficios.setBounds(490, 230, 120, 25);

        jtxtOutrosBeneficios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtOutrosBeneficios);
        jtxtOutrosBeneficios.setBounds(620, 230, 340, 25);

        jlblNumeroBpcloas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNumeroBpcloas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNumeroBpcloas.setText("Núm. BPCLOAS:");
        jlblNumeroBpcloas.setToolTipText("Número do BPCLOAS");
        jpnlDadosProfissionais.add(jlblNumeroBpcloas);
        jlblNumeroBpcloas.setBounds(490, 260, 120, 25);

        jtxtNumeroBpcloas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosProfissionais.add(jtxtNumeroBpcloas);
        jtxtNumeroBpcloas.setBounds(620, 260, 340, 25);

        jpnlEscolaridadeProfissionalWrapper.add(jpnlDadosProfissionais);
        jpnlDadosProfissionais.setBounds(10, 110, 970, 390);

        jpnlEscolaridadeProfissional.add(jpnlEscolaridadeProfissionalWrapper);
        jpnlEscolaridadeProfissionalWrapper.setBounds(0, 0, 990, 500);

        jtbpFormulario.addTab("Escolaridade/Profissional", null, jpnlEscolaridadeProfissional, "Dados Escolares e Profissionais do Indivíduo");

        jpnlDeficiencia.setToolTipText("");
        jpnlDeficiencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDeficiencia.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlDeficienciaComponentResized(evt);
            }
        });
        jpnlDeficiencia.setLayout(null);

        jpnlDeficienciaWrapper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDeficienciaWrapper.setLayout(null);

        jlblDeficiente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDeficiente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblDeficiente.setText("É Deficiente:");
        jlblDeficiente.setToolTipText("O Indivíduo Apresenta Algum Tipo de Deficiência?");
        jpnlDeficienciaWrapper.add(jlblDeficiente);
        jlblDeficiente.setBounds(10, 20, 120, 25);

        jcbbDeficiente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbDeficiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Sim", "Não" }));
        jpnlDeficienciaWrapper.add(jcbbDeficiente);
        jcbbDeficiente.setBounds(140, 20, 350, 25);

        jpnlTipoDeficiencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Deficiência"));
        jpnlTipoDeficiencia.setLayout(null);

        jbtgDeficienciaVisual.add(jckbCegueira);
        jckbCegueira.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbCegueira.setText("Cegueira");
        jckbCegueira.setToolTipText("Cegueira Total");
        jpnlTipoDeficiencia.add(jckbCegueira);
        jckbCegueira.setBounds(10, 20, 100, 25);

        jbtgDeficienciaVisual.add(jckbBaixaVisao);
        jckbBaixaVisao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbBaixaVisao.setText("Baixa Visão");
        jckbBaixaVisao.setToolTipText("Cegueira Parcial");
        jpnlTipoDeficiencia.add(jckbBaixaVisao);
        jckbBaixaVisao.setBounds(10, 50, 100, 25);

        jckbDeficienciaFisica.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbDeficienciaFisica.setText("Deficiência Física");
        jckbDeficienciaFisica.setToolTipText("Deficiência Física (Imobilidade ou Perda de Membros)");
        jpnlTipoDeficiencia.add(jckbDeficienciaFisica);
        jckbDeficienciaFisica.setBounds(10, 80, 200, 25);

        jckbSindromeDown.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSindromeDown.setText("Síndrome de Down");
        jckbSindromeDown.setToolTipText("É Portador de Síndrome de Down");
        jpnlTipoDeficiencia.add(jckbSindromeDown);
        jckbSindromeDown.setBounds(10, 110, 180, 25);

        jbtgDeficienciaAuditiva.add(jckbSurdezSevera);
        jckbSurdezSevera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSurdezSevera.setText("Surdez Severa/Profunda");
        jckbSurdezSevera.setToolTipText("Deficiência Auditiva Total ou Avançada");
        jpnlTipoDeficiencia.add(jckbSurdezSevera);
        jckbSurdezSevera.setBounds(230, 20, 220, 25);

        jbtgDeficienciaAuditiva.add(jckbSurdezLeve);
        jckbSurdezLeve.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSurdezLeve.setText("Surdez Leve/Moderada");
        jckbSurdezLeve.setToolTipText("De Baixo à Médio Grau de Deficiência Auditiva");
        jpnlTipoDeficiencia.add(jckbSurdezLeve);
        jckbSurdezLeve.setBounds(230, 50, 220, 25);

        jckbDeficienciaMental.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbDeficienciaMental.setText("Deficiência Mental/Intelectual");
        jpnlTipoDeficiencia.add(jckbDeficienciaMental);
        jckbDeficienciaMental.setBounds(230, 80, 220, 25);

        jckbTranstornoMental.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbTranstornoMental.setText("Transtorno/Doença Mental");
        jpnlTipoDeficiencia.add(jckbTranstornoMental);
        jckbTranstornoMental.setBounds(230, 110, 220, 25);

        jpnlDeficienciaWrapper.add(jpnlTipoDeficiencia);
        jpnlTipoDeficiencia.setBounds(10, 50, 480, 170);

        jlblObsTipoDeficiencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblObsTipoDeficiencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblObsTipoDeficiencia.setText("Observ. Tipo:");
        jlblObsTipoDeficiencia.setToolTipText("Observações Referentes ao(s) Tipo(s) de Deficiência(s) do Indivíduo");
        jpnlDeficienciaWrapper.add(jlblObsTipoDeficiencia);
        jlblObsTipoDeficiencia.setBounds(10, 230, 120, 25);

        jtxtaObsTipoDeficiencia.setColumns(20);
        jtxtaObsTipoDeficiencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtaObsTipoDeficiencia.setRows(5);
        jscpTextAreaObsTipoDeficiencia.setViewportView(jtxtaObsTipoDeficiencia);

        javax.swing.GroupLayout jpnlTextAreaObsTipoDeficienciaLayout = new javax.swing.GroupLayout(jpnlTextAreaObsTipoDeficiencia);
        jpnlTextAreaObsTipoDeficiencia.setLayout(jpnlTextAreaObsTipoDeficienciaLayout);
        jpnlTextAreaObsTipoDeficienciaLayout.setHorizontalGroup(
            jpnlTextAreaObsTipoDeficienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsTipoDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jpnlTextAreaObsTipoDeficienciaLayout.setVerticalGroup(
            jpnlTextAreaObsTipoDeficienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsTipoDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        jpnlDeficienciaWrapper.add(jpnlTextAreaObsTipoDeficiencia);
        jpnlTextAreaObsTipoDeficiencia.setBounds(140, 230, 350, 260);

        jlblCausaDeficiencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblCausaDeficiencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCausaDeficiencia.setText("Causa Deficiência:");
        jlblCausaDeficiencia.setToolTipText("Causa da Deficiência do Indivíduo");
        jpnlDeficienciaWrapper.add(jlblCausaDeficiencia);
        jlblCausaDeficiencia.setBounds(500, 20, 120, 25);

        jtxtCausaDeficiencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDeficienciaWrapper.add(jtxtCausaDeficiencia);
        jtxtCausaDeficiencia.setBounds(630, 20, 350, 25);

        jlblObsCausaDeficiencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblObsCausaDeficiencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblObsCausaDeficiencia.setText("Observ. Causa:");
        jlblObsCausaDeficiencia.setToolTipText("Observações Referentes à Causa da Deficiência do Indivíduo");
        jpnlDeficienciaWrapper.add(jlblObsCausaDeficiencia);
        jlblObsCausaDeficiencia.setBounds(490, 50, 120, 25);

        jtxtaObsCausaDeficiencia.setColumns(20);
        jtxtaObsCausaDeficiencia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtxtaObsCausaDeficiencia.setRows(5);
        jscpTextAreaObsCausaDeficiencia.setViewportView(jtxtaObsCausaDeficiencia);

        javax.swing.GroupLayout jpnlTextAreaObsCausaDeficienciaLayout = new javax.swing.GroupLayout(jpnlTextAreaObsCausaDeficiencia);
        jpnlTextAreaObsCausaDeficiencia.setLayout(jpnlTextAreaObsCausaDeficienciaLayout);
        jpnlTextAreaObsCausaDeficienciaLayout.setHorizontalGroup(
            jpnlTextAreaObsCausaDeficienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsCausaDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jpnlTextAreaObsCausaDeficienciaLayout.setVerticalGroup(
            jpnlTextAreaObsCausaDeficienciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTextAreaObsCausaDeficiencia, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        jpnlDeficienciaWrapper.add(jpnlTextAreaObsCausaDeficiencia);
        jpnlTextAreaObsCausaDeficiencia.setBounds(630, 50, 350, 240);

        jlblQuandoAdquiriu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblQuandoAdquiriu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblQuandoAdquiriu.setText("Quando adquiriu:");
        jlblQuandoAdquiriu.setToolTipText("Quando o Indivíduo Adquiriu a(s) Deficiência(s)");
        jpnlDeficienciaWrapper.add(jlblQuandoAdquiriu);
        jlblQuandoAdquiriu.setBounds(500, 300, 120, 25);

        jtxtQuandoAdquiriu.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDeficienciaWrapper.add(jtxtQuandoAdquiriu);
        jtxtQuandoAdquiriu.setBounds(630, 300, 350, 25);

        jpnlDependeCuidados.setBorder(javax.swing.BorderFactory.createTitledBorder("Depende de Cuidados"));
        jpnlDependeCuidados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDependeCuidados.setLayout(null);

        jckbNaoDepende.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbNaoDepende.setText("Não");
        jckbNaoDepende.setToolTipText("Não Depende de Cuidados");
        jpnlDependeCuidados.add(jckbNaoDepende);
        jckbNaoDepende.setBounds(10, 20, 200, 25);

        jckbSimAlguemFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSimAlguemFamilia.setText("Sim, Alguém da Família");
        jckbSimAlguemFamilia.setToolTipText("Depende de Cuidados de Pessoas da Própria Família");
        jpnlDependeCuidados.add(jckbSimAlguemFamilia);
        jckbSimAlguemFamilia.setBounds(10, 50, 200, 25);

        jckbSimCuidadorEspecializado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSimCuidadorEspecializado.setText("Sim, Cuidador Especializado");
        jckbSimCuidadorEspecializado.setToolTipText("Depende de Cuidador Especializado");
        jpnlDependeCuidados.add(jckbSimCuidadorEspecializado);
        jckbSimCuidadorEspecializado.setBounds(10, 80, 200, 25);

        jckbSimVizinho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSimVizinho.setText("Sim, Vizinho");
        jckbSimVizinho.setToolTipText("Depende de Cuidados de Vizinhos");
        jpnlDependeCuidados.add(jckbSimVizinho);
        jckbSimVizinho.setBounds(230, 20, 230, 25);

        jckbSimInstituicao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSimInstituicao.setText("Sim, Instituição Socioassistencial");
        jckbSimInstituicao.setToolTipText("Depende de Cuidado de Instituição ou de Rede Socioassistêncial");
        jpnlDependeCuidados.add(jckbSimInstituicao);
        jckbSimInstituicao.setBounds(230, 50, 230, 25);

        jckbSimOutraForma.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jckbSimOutraForma.setText("Sim, Outra Forma");
        jckbSimOutraForma.setToolTipText("Depende de Outros Tipos de Cuidados");
        jpnlDependeCuidados.add(jckbSimOutraForma);
        jckbSimOutraForma.setBounds(230, 80, 230, 25);

        jpnlDeficienciaWrapper.add(jpnlDependeCuidados);
        jpnlDependeCuidados.setBounds(500, 330, 480, 120);

        jlblCadastroSepedi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblCadastroSepedi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblCadastroSepedi.setText("Cadastro SEPEDI:");
        jlblCadastroSepedi.setToolTipText("O Indivíduo Possui Cadastro na SEPEDI?");
        jpnlDeficienciaWrapper.add(jlblCadastroSepedi);
        jlblCadastroSepedi.setBounds(500, 460, 120, 25);

        jcbbCadastroSepedi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbCadastroSepedi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Sim", "Não" }));
        jpnlDeficienciaWrapper.add(jcbbCadastroSepedi);
        jcbbCadastroSepedi.setBounds(630, 460, 350, 25);

        jpnlDeficiencia.add(jpnlDeficienciaWrapper);
        jpnlDeficienciaWrapper.setBounds(0, 0, 990, 500);

        jtbpFormulario.addTab("Deficiência", null, jpnlDeficiencia, "Dados de Deficiência(s) do Indivíduo");

        jpnlRodape.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlRodape.setLayout(null);

        jpnlRodapeWrapper.setLayout(null);

        jbtnNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/new.png"))); // NOI18N
        jbtnNovo.setText("Novo");
        jbtnNovo.setToolTipText("Novo Registro");
        jbtnNovo.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnNovo);
        jbtnNovo.setBounds(470, 10, 120, 30);

        jbtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/save.png"))); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setToolTipText("Cadastrar o Novo Registro");
        jbtnSalvar.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnSalvar);
        jbtnSalvar.setBounds(600, 10, 120, 30);

        jbtnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/edit.png"))); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.setToolTipText("Editar o Registro Atual");
        jbtnEditar.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnEditar);
        jbtnEditar.setBounds(730, 10, 120, 30);

        jbtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/delete.png"))); // NOI18N
        jbtnExcluir.setText("Excluir");
        jbtnExcluir.setToolTipText("Excluir o Registro Atual");
        jbtnExcluir.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnExcluir);
        jbtnExcluir.setBounds(860, 10, 120, 30);

        jpnlRodape.add(jpnlRodapeWrapper);
        jpnlRodapeWrapper.setBounds(0, 0, 1000, 50);

        javax.swing.GroupLayout jpnlFormularioLayout = new javax.swing.GroupLayout(jpnlFormulario);
        jpnlFormulario.setLayout(jpnlFormularioLayout);
        jpnlFormularioLayout.setHorizontalGroup(
            jpnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
            .addComponent(jpnlRodape, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnlFormularioLayout.setVerticalGroup(
            jpnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFormularioLayout.createSequentialGroup()
                .addComponent(jtbpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtbpPrincipal.addTab("Indivíduo", null, jpnlFormulario, "Dados do Indivíduo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnlDadosIndividuoComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlDadosIndividuoComponentResized
        
        jpnlDadosIndividuoWrapper.setSize(990, 500);
        int parentWidth = jpnlDadosIndividuo.getWidth();
        int childWidth = jpnlDadosIndividuoWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlDadosIndividuoWrapper.setBounds(newLocation, 0, 990, jpnlDadosIndividuoWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlDadosIndividuoComponentResized

    private void jpnlDocumentosCertidaoComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlDocumentosCertidaoComponentResized
        
        jpnlDocumentosCertidaoWrapper.setSize(990, 500);
        int parentWidth = jpnlDocumentosCertidao.getWidth();
        int childWidth = jpnlDocumentosCertidaoWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlDocumentosCertidaoWrapper.setBounds(newLocation, 0, 990, jpnlDocumentosCertidaoWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlDocumentosCertidaoComponentResized

    private void jpnlEscolaridadeProfissionalComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlEscolaridadeProfissionalComponentResized
        
        jpnlEscolaridadeProfissionalWrapper.setSize(990, 500);
        int parentWidth = jpnlEscolaridadeProfissional.getWidth();
        int childWidth = jpnlEscolaridadeProfissionalWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlEscolaridadeProfissionalWrapper.setBounds(newLocation, 0, 990, jpnlEscolaridadeProfissionalWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlEscolaridadeProfissionalComponentResized

    private void jpnlDeficienciaComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlDeficienciaComponentResized
        
        jpnlDeficienciaWrapper.setSize(990, 500);
        int parentWidth = jpnlDeficiencia.getWidth();
        int childWidth = jpnlDeficienciaWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlDeficienciaWrapper.setBounds(newLocation, 0, 990, jpnlDeficienciaWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlDeficienciaComponentResized

    private void jpnlFormularioComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlFormularioComponentResized
        
        jpnlRodapeWrapper.setSize(990, 50);
        int parentWidth = jpnlRodape.getWidth();
        int childWidth = jpnlRodapeWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlRodapeWrapper.setBounds(newLocation, 0, 990, jpnlRodapeWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlFormularioComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jbtgDeficienciaAuditiva;
    private javax.swing.ButtonGroup jbtgDeficienciaVisual;
    private javax.swing.JButton jbtnAnexos;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnGerenciarDocumentos;
    private javax.swing.JButton jbtnGerenciarTelefones;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnPesquisar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox jcbbCadastroSepedi;
    private javax.swing.JComboBox jcbbDeficiente;
    private javax.swing.JComboBox jcbbEstadoCivil;
    private javax.swing.JComboBox jcbbEtinia;
    private javax.swing.JComboBox jcbbFamilia;
    private javax.swing.JComboBox jcbbFiltro;
    private javax.swing.JComboBox jcbbGrauEscolaridade;
    private javax.swing.JComboBox jcbbGrauParentesco;
    private javax.swing.JComboBox jcbbLeEscreve;
    private javax.swing.JComboBox jcbbMunicipioCertidao;
    private javax.swing.JComboBox jcbbNascimentoRegistrado;
    private javax.swing.JComboBox jcbbPossuiRenda;
    private javax.swing.JComboBox jcbbResponsavelFamilia;
    private javax.swing.JComboBox jcbbSexo;
    private javax.swing.JComboBox jcbbSituacaoProfissional;
    private javax.swing.JComboBox jcbbTipoCertidao;
    private javax.swing.JComboBox jcbbUfCertidao;
    private javax.swing.JCheckBox jckbBaixaVisao;
    private javax.swing.JCheckBox jckbCegueira;
    private javax.swing.JCheckBox jckbDeficienciaFisica;
    private javax.swing.JCheckBox jckbDeficienciaMental;
    private javax.swing.JCheckBox jckbNaoDepende;
    private javax.swing.JCheckBox jckbSimAlguemFamilia;
    private javax.swing.JCheckBox jckbSimCuidadorEspecializado;
    private javax.swing.JCheckBox jckbSimInstituicao;
    private javax.swing.JCheckBox jckbSimOutraForma;
    private javax.swing.JCheckBox jckbSimVizinho;
    private javax.swing.JCheckBox jckbSindromeDown;
    private javax.swing.JCheckBox jckbSurdezLeve;
    private javax.swing.JCheckBox jckbSurdezSevera;
    private javax.swing.JCheckBox jckbTranstornoMental;
    private javax.swing.JLabel jlblAnexos;
    private javax.swing.JLabel jlblApelido;
    private javax.swing.JLabel jlblAposentadoriaPensao;
    private javax.swing.JLabel jlblCadastroSepedi;
    private javax.swing.JLabel jlblCausaDeficiencia;
    private javax.swing.JLabel jlblCodigoCartorio;
    private javax.swing.JLabel jlblCpfInformante;
    private javax.swing.JLabel jlblDataNascimento;
    private javax.swing.JLabel jlblDataRegistro;
    private javax.swing.JLabel jlblDeficiente;
    private javax.swing.JLabel jlblDoacaoRegular;
    private javax.swing.JLabel jlblEstadoCivil;
    private javax.swing.JLabel jlblEtinia;
    private javax.swing.JLabel jlblFamilia;
    private javax.swing.JLabel jlblFiltro;
    private javax.swing.JLabel jlblGrauEscolaridade;
    private javax.swing.JLabel jlblGrauParentesco;
    private javax.swing.JLabel jlblIdade;
    private javax.swing.JLabel jlblLeEscreve;
    private javax.swing.JLabel jlblMunicipioCertidao;
    private javax.swing.JLabel jlblNascimentoRegistrado;
    private javax.swing.JLabel jlblNaturalidade;
    private javax.swing.JLabel jlblNome;
    private javax.swing.JLabel jlblNomeCartorio;
    private javax.swing.JLabel jlblNomeMae;
    private javax.swing.JLabel jlblNomePai;
    private javax.swing.JLabel jlblNomeTrabalho;
    private javax.swing.JLabel jlblNumeroBpcloas;
    private javax.swing.JLabel jlblNumeroFolha;
    private javax.swing.JLabel jlblNumeroLivro;
    private javax.swing.JLabel jlblNumeroTermo;
    private javax.swing.JLabel jlblObsCausaDeficiencia;
    private javax.swing.JLabel jlblObsSituacao;
    private javax.swing.JLabel jlblObsTipo;
    private javax.swing.JLabel jlblObsTipoDeficiencia;
    private javax.swing.JLabel jlblOndeNasceu;
    private javax.swing.JLabel jlblOutrosBeneficios;
    private javax.swing.JLabel jlblPensaoAlimentar;
    private javax.swing.JLabel jlblPesquisa;
    private javax.swing.JLabel jlblPossuiRenda;
    private javax.swing.JLabel jlblPrestouInformacao;
    private javax.swing.JLabel jlblQuandoAdquiriu;
    private javax.swing.JLabel jlblRenda;
    private javax.swing.JLabel jlblResponsavel;
    private javax.swing.JLabel jlblResponsavelFamilia;
    private javax.swing.JLabel jlblSeguroDesemprego;
    private javax.swing.JLabel jlblSexo;
    private javax.swing.JLabel jlblSituacaoProfissional;
    private javax.swing.JLabel jlblTipoCertidao;
    private javax.swing.JLabel jlblTipoTrabalho;
    private javax.swing.JLabel jlblUfCertidao;
    private javax.swing.JLabel jlblUnidadeEducacional;
    private javax.swing.JList jlstTelefones;
    private javax.swing.JPanel jpnlCertidao;
    private javax.swing.JPanel jpnlDadosEscolares;
    private javax.swing.JPanel jpnlDadosIndividuo;
    private javax.swing.JPanel jpnlDadosIndividuoWrapper;
    private javax.swing.JPanel jpnlDadosProfissionais;
    private javax.swing.JPanel jpnlDeficiencia;
    private javax.swing.JPanel jpnlDeficienciaWrapper;
    private javax.swing.JPanel jpnlDependeCuidados;
    private javax.swing.JPanel jpnlDocumentosCertidao;
    private javax.swing.JPanel jpnlDocumentosCertidaoWrapper;
    private javax.swing.JPanel jpnlEscolaridadeProfissional;
    private javax.swing.JPanel jpnlEscolaridadeProfissionalWrapper;
    private javax.swing.JPanel jpnlFormulario;
    private javax.swing.JPanel jpnlListaTelefones;
    private javax.swing.JPanel jpnlPesquisa;
    private javax.swing.JPanel jpnlPesquisar;
    private javax.swing.JPanel jpnlRodape;
    private javax.swing.JPanel jpnlRodapeWrapper;
    private javax.swing.JPanel jpnlTabelaDocumentos;
    private javax.swing.JPanel jpnlTextAreaObsCausaDeficiencia;
    private javax.swing.JPanel jpnlTextAreaObsIndividuo;
    private javax.swing.JPanel jpnlTextAreaObsSituacao;
    private javax.swing.JPanel jpnlTextAreaObsTipo;
    private javax.swing.JPanel jpnlTextAreaObsTipoDeficiencia;
    private javax.swing.JPanel jpnlTipoDeficiencia;
    private javax.swing.JScrollPane jscpListaTelefones;
    private javax.swing.JScrollPane jscpTabelaDocumentos;
    private javax.swing.JScrollPane jscpTabelaPesquisa;
    private javax.swing.JScrollPane jscpTextAreaObsCausaDeficiencia;
    private javax.swing.JScrollPane jscpTextAreaObsIndividuo;
    private javax.swing.JScrollPane jscpTextAreaObsSituacao;
    private javax.swing.JScrollPane jscpTextAreaObsTipo;
    private javax.swing.JScrollPane jscpTextAreaObsTipoDeficiencia;
    private javax.swing.JTable jtblDocumentos;
    private javax.swing.JTable jtblPesquisa;
    private javax.swing.JTabbedPane jtbpFormulario;
    private javax.swing.JTabbedPane jtbpPrincipal;
    private javax.swing.JTextField jtxtAnexos;
    private javax.swing.JTextField jtxtApelido;
    private javax.swing.JTextField jtxtAposentadoriaPensao;
    private javax.swing.JTextField jtxtCausaDeficiencia;
    private javax.swing.JTextField jtxtCodigoCartorio;
    private javax.swing.JFormattedTextField jtxtCpfInformante;
    private javax.swing.JFormattedTextField jtxtDataNascimento;
    private javax.swing.JFormattedTextField jtxtDataRegistro;
    private javax.swing.JTextField jtxtDoacaoRegular;
    private javax.swing.JTextField jtxtIdade;
    private javax.swing.JTextField jtxtNaturalidade;
    private javax.swing.JTextField jtxtNome;
    private javax.swing.JTextField jtxtNomeCartorio;
    private javax.swing.JTextField jtxtNomeMae;
    private javax.swing.JTextField jtxtNomePai;
    private javax.swing.JTextField jtxtNomeTrabalho;
    private javax.swing.JTextField jtxtNumeroBpcloas;
    private javax.swing.JTextField jtxtNumeroFolha;
    private javax.swing.JTextField jtxtNumeroLivro;
    private javax.swing.JTextField jtxtNumeroTermo;
    private javax.swing.JTextField jtxtOndeNasceu;
    private javax.swing.JTextField jtxtOutrosBeneficios;
    private javax.swing.JTextField jtxtPensaoAlimentar;
    private javax.swing.JTextField jtxtPesquisa;
    private javax.swing.JTextField jtxtPrestouInformacao;
    private javax.swing.JTextField jtxtQuandoAdquiriu;
    private javax.swing.JTextField jtxtRenda;
    private javax.swing.JTextField jtxtResponsavel;
    private javax.swing.JTextField jtxtSeguroDesemprego;
    private javax.swing.JTextField jtxtTipoTrabalho;
    private javax.swing.JTextField jtxtUnidadeEducacional;
    private javax.swing.JTextArea jtxtaObsCausaDeficiencia;
    private javax.swing.JTextArea jtxtaObsIndividuo;
    private javax.swing.JTextArea jtxtaObsSituacao;
    private javax.swing.JTextArea jtxtaObsTipo;
    private javax.swing.JTextArea jtxtaObsTipoDeficiencia;
    // End of variables declaration//GEN-END:variables
}
