/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormGerenciarEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGerenciarEmpresa
     */
    public FormGerenciarEmpresa() {
        
        initComponents();
        
        try {
            
            com.sys.SystemSettings.setSystemThemeNimbus();
            
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsepPrincipal = new javax.swing.JScrollPane();
        jtbpPrincipal = new javax.swing.JTabbedPane();
        jpnlPesquisa = new javax.swing.JPanel();
        jpnlPesquisar = new javax.swing.JPanel();
        jlblPesquisa = new javax.swing.JLabel();
        jtxtPesquisa = new javax.swing.JTextField();
        jlblFiltro = new javax.swing.JLabel();
        jcbbFiltro = new javax.swing.JComboBox();
        jbtnPesquisar = new javax.swing.JButton();
        jscpTabelaPesquisa = new javax.swing.JScrollPane();
        jtblPesquisa = new javax.swing.JTable();
        jpnlFormulario = new javax.swing.JPanel();
        jtbpFormulario = new javax.swing.JTabbedPane();
        jpnlDadosEmpresa = new javax.swing.JPanel();
        jpnlDadosEmpresaWrapper = new javax.swing.JPanel();
        jlblRazaoSocial = new javax.swing.JLabel();
        jtxtRazaoSocial = new javax.swing.JTextField();
        jlblNomeFantasia = new javax.swing.JLabel();
        jtxtNomeFantasia = new javax.swing.JTextField();
        jlblFundador = new javax.swing.JLabel();
        jtxtFundador = new javax.swing.JTextField();
        jlblDataFundacao = new javax.swing.JLabel();
        jtxtDataFundacao = new javax.swing.JFormattedTextField();
        jlblLocalOrigem = new javax.swing.JLabel();
        jtxtLocalOrigem = new javax.swing.JTextField();
        jpnlTelefones = new javax.swing.JPanel();
        jbtnGerenciarTelefones = new javax.swing.JButton();
        jpnlListaTelefones = new javax.swing.JPanel();
        jscpListaTelefones = new javax.swing.JScrollPane();
        jlstTelefones = new javax.swing.JList();
        jpnlDocumentos = new javax.swing.JPanel();
        jpnlDocumentosWrapper = new javax.swing.JPanel();
        jpnlTabelaDocumentos = new javax.swing.JPanel();
        jscpTabelaDocumentos = new javax.swing.JScrollPane();
        jtblDocumentos = new javax.swing.JTable();
        jbtnGerenciarDocumentos = new javax.swing.JButton();
        jpnlRodape = new javax.swing.JPanel();
        jpnlRodapeWrapper = new javax.swing.JPanel();
        jbtnNovo = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CadHab - Gerenciamento de Empresas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/building.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(65355, 65355));
        setMinimumSize(new java.awt.Dimension(0, 0));

        jsepPrincipal.setAutoscrolls(true);
        jsepPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtbpPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlPesquisar.setLayout(null);

        jlblPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblPesquisa.setText("Pesquisa:");
        jpnlPesquisar.add(jlblPesquisa);
        jlblPesquisa.setBounds(0, 10, 70, 25);

        jtxtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPesquisar.add(jtxtPesquisa);
        jtxtPesquisa.setBounds(70, 10, 270, 25);

        jlblFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblFiltro.setText("Filtrar Por:");
        jpnlPesquisar.add(jlblFiltro);
        jlblFiltro.setBounds(360, 10, 70, 25);

        jcbbFiltro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sem filtro" }));
        jpnlPesquisar.add(jcbbFiltro);
        jcbbFiltro.setBounds(430, 10, 200, 25);

        jbtnPesquisar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/search.png"))); // NOI18N
        jbtnPesquisar.setText("Pesquisar");
        jpnlPesquisar.add(jbtnPesquisar);
        jbtnPesquisar.setBounds(640, 10, 120, 30);

        jtblPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscpTabelaPesquisa.setViewportView(jtblPesquisa);

        javax.swing.GroupLayout jpnlPesquisaLayout = new javax.swing.GroupLayout(jpnlPesquisa);
        jpnlPesquisa.setLayout(jpnlPesquisaLayout);
        jpnlPesquisaLayout.setHorizontalGroup(
            jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscpTabelaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnlPesquisaLayout.setVerticalGroup(
            jpnlPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpTabelaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );

        jtbpPrincipal.addTab("Pesquisa", jpnlPesquisa);

        jpnlFormulario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlFormulario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlFormularioComponentResized(evt);
            }
        });

        jtbpFormulario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jpnlDadosEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEmpresa.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlDadosEmpresaComponentResized(evt);
            }
        });
        jpnlDadosEmpresa.setLayout(null);

        jpnlDadosEmpresaWrapper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEmpresaWrapper.setLayout(null);

        jlblRazaoSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblRazaoSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblRazaoSocial.setText("Razão Social:");
        jpnlDadosEmpresaWrapper.add(jlblRazaoSocial);
        jlblRazaoSocial.setBounds(10, 10, 120, 25);

        jtxtRazaoSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEmpresaWrapper.add(jtxtRazaoSocial);
        jtxtRazaoSocial.setBounds(140, 10, 620, 25);

        jlblNomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNomeFantasia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNomeFantasia.setText("Nome Fantasia:");
        jpnlDadosEmpresaWrapper.add(jlblNomeFantasia);
        jlblNomeFantasia.setBounds(10, 40, 120, 25);

        jtxtNomeFantasia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEmpresaWrapper.add(jtxtNomeFantasia);
        jtxtNomeFantasia.setBounds(140, 40, 620, 25);

        jlblFundador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblFundador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblFundador.setText("Fundador:");
        jpnlDadosEmpresaWrapper.add(jlblFundador);
        jlblFundador.setBounds(10, 70, 120, 25);

        jtxtFundador.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEmpresaWrapper.add(jtxtFundador);
        jtxtFundador.setBounds(140, 70, 620, 25);

        jlblDataFundacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDataFundacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblDataFundacao.setText("Data Fundação:");
        jpnlDadosEmpresaWrapper.add(jlblDataFundacao);
        jlblDataFundacao.setBounds(10, 100, 120, 25);

        jtxtDataFundacao.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jpnlDadosEmpresaWrapper.add(jtxtDataFundacao);
        jtxtDataFundacao.setBounds(140, 100, 620, 25);

        jlblLocalOrigem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblLocalOrigem.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblLocalOrigem.setText("Local Origem:");
        jpnlDadosEmpresaWrapper.add(jlblLocalOrigem);
        jlblLocalOrigem.setBounds(10, 130, 120, 25);

        jtxtLocalOrigem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDadosEmpresaWrapper.add(jtxtLocalOrigem);
        jtxtLocalOrigem.setBounds(140, 130, 620, 25);

        jpnlTelefones.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefones"));
        jpnlTelefones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlTelefones.setLayout(null);

        jbtnGerenciarTelefones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnGerenciarTelefones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/manage.png"))); // NOI18N
        jpnlTelefones.add(jbtnGerenciarTelefones);
        jbtnGerenciarTelefones.setBounds(710, 20, 25, 25);

        jscpListaTelefones.setViewportView(jlstTelefones);

        javax.swing.GroupLayout jpnlListaTelefonesLayout = new javax.swing.GroupLayout(jpnlListaTelefones);
        jpnlListaTelefones.setLayout(jpnlListaTelefonesLayout);
        jpnlListaTelefonesLayout.setHorizontalGroup(
            jpnlListaTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpListaTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jpnlListaTelefonesLayout.setVerticalGroup(
            jpnlListaTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpListaTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        jpnlTelefones.add(jpnlListaTelefones);
        jpnlListaTelefones.setBounds(10, 20, 690, 140);

        jpnlDadosEmpresaWrapper.add(jpnlTelefones);
        jpnlTelefones.setBounds(10, 170, 750, 170);

        jpnlDadosEmpresa.add(jpnlDadosEmpresaWrapper);
        jpnlDadosEmpresaWrapper.setBounds(0, 0, 774, 357);

        jtbpFormulario.addTab("Dados da Empresa", jpnlDadosEmpresa);

        jpnlDocumentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDocumentos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlDocumentosComponentResized(evt);
            }
        });
        jpnlDocumentos.setLayout(null);

        jpnlDocumentosWrapper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlDocumentosWrapper.setLayout(null);

        jpnlTabelaDocumentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jtblDocumentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtblDocumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscpTabelaDocumentos.setViewportView(jtblDocumentos);

        javax.swing.GroupLayout jpnlTabelaDocumentosLayout = new javax.swing.GroupLayout(jpnlTabelaDocumentos);
        jpnlTabelaDocumentos.setLayout(jpnlTabelaDocumentosLayout);
        jpnlTabelaDocumentosLayout.setHorizontalGroup(
            jpnlTabelaDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTabelaDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jpnlTabelaDocumentosLayout.setVerticalGroup(
            jpnlTabelaDocumentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTabelaDocumentos, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        jpnlDocumentosWrapper.add(jpnlTabelaDocumentos);
        jpnlTabelaDocumentos.setBounds(10, 10, 720, 330);

        jbtnGerenciarDocumentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnGerenciarDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/manage.png"))); // NOI18N
        jpnlDocumentosWrapper.add(jbtnGerenciarDocumentos);
        jbtnGerenciarDocumentos.setBounds(740, 10, 25, 25);

        jpnlDocumentos.add(jpnlDocumentosWrapper);
        jpnlDocumentosWrapper.setBounds(0, 0, 774, 357);

        jtbpFormulario.addTab("Documentos", jpnlDocumentos);

        jpnlRodape.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlRodape.setLayout(null);

        jpnlRodapeWrapper.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlRodapeWrapper.setLayout(null);

        jbtnNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/new.png"))); // NOI18N
        jbtnNovo.setText("Novo");
        jbtnNovo.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnNovo);
        jbtnNovo.setBounds(260, 10, 120, 30);

        jbtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/save.png"))); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnSalvar);
        jbtnSalvar.setBounds(390, 10, 120, 30);

        jbtnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/edit.png"))); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnEditar);
        jbtnEditar.setBounds(520, 10, 120, 30);

        jbtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/delete.png"))); // NOI18N
        jbtnExcluir.setText("Excluir");
        jbtnExcluir.setIconTextGap(10);
        jpnlRodapeWrapper.add(jbtnExcluir);
        jbtnExcluir.setBounds(650, 10, 120, 30);

        jpnlRodape.add(jpnlRodapeWrapper);
        jpnlRodapeWrapper.setBounds(0, 0, 780, 50);

        javax.swing.GroupLayout jpnlFormularioLayout = new javax.swing.GroupLayout(jpnlFormulario);
        jpnlFormulario.setLayout(jpnlFormularioLayout);
        jpnlFormularioLayout.setHorizontalGroup(
            jpnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtbpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addComponent(jpnlRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnlFormularioLayout.setVerticalGroup(
            jpnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFormularioLayout.createSequentialGroup()
                .addComponent(jtbpFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlRodape, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jtbpPrincipal.addTab("Empresa", jpnlFormulario);

        jsepPrincipal.setViewportView(jtbpPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jsepPrincipal)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jsepPrincipal)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnlDadosEmpresaComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlDadosEmpresaComponentResized
        
        jpnlDadosEmpresaWrapper.setSize(774, 357);
        int parentWidth = jpnlDadosEmpresa.getWidth();
        int childWidth = jpnlDadosEmpresaWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlDadosEmpresaWrapper.setBounds(newLocation, 0, 774, jpnlDadosEmpresaWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlDadosEmpresaComponentResized

    private void jpnlDocumentosComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlDocumentosComponentResized
        
        jpnlDocumentosWrapper.setSize(774, 357);
        int parentWidth = jpnlDocumentos.getWidth();
        int childWidth = jpnlDocumentosWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlDocumentosWrapper.setBounds(newLocation, 0, 774, jpnlDocumentosWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlDocumentosComponentResized

    private void jpnlFormularioComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlFormularioComponentResized
        
        jpnlRodapeWrapper.setSize(774, 50);
        int parentWidth = jpnlRodape.getWidth();
        int childWidth = jpnlRodapeWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlRodapeWrapper.setBounds(newLocation, 0, 774, jpnlRodapeWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlFormularioComponentResized

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnGerenciarDocumentos;
    private javax.swing.JButton jbtnGerenciarTelefones;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnPesquisar;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox jcbbFiltro;
    private javax.swing.JLabel jlblDataFundacao;
    private javax.swing.JLabel jlblFiltro;
    private javax.swing.JLabel jlblFundador;
    private javax.swing.JLabel jlblLocalOrigem;
    private javax.swing.JLabel jlblNomeFantasia;
    private javax.swing.JLabel jlblPesquisa;
    private javax.swing.JLabel jlblRazaoSocial;
    private javax.swing.JList jlstTelefones;
    private javax.swing.JPanel jpnlDadosEmpresa;
    private javax.swing.JPanel jpnlDadosEmpresaWrapper;
    private javax.swing.JPanel jpnlDocumentos;
    private javax.swing.JPanel jpnlDocumentosWrapper;
    private javax.swing.JPanel jpnlFormulario;
    private javax.swing.JPanel jpnlListaTelefones;
    private javax.swing.JPanel jpnlPesquisa;
    private javax.swing.JPanel jpnlPesquisar;
    private javax.swing.JPanel jpnlRodape;
    private javax.swing.JPanel jpnlRodapeWrapper;
    private javax.swing.JPanel jpnlTabelaDocumentos;
    private javax.swing.JPanel jpnlTelefones;
    private javax.swing.JScrollPane jscpListaTelefones;
    private javax.swing.JScrollPane jscpTabelaDocumentos;
    private javax.swing.JScrollPane jscpTabelaPesquisa;
    private javax.swing.JScrollPane jsepPrincipal;
    private javax.swing.JTable jtblDocumentos;
    private javax.swing.JTable jtblPesquisa;
    private javax.swing.JTabbedPane jtbpFormulario;
    private javax.swing.JTabbedPane jtbpPrincipal;
    private javax.swing.JFormattedTextField jtxtDataFundacao;
    private javax.swing.JTextField jtxtFundador;
    private javax.swing.JTextField jtxtLocalOrigem;
    private javax.swing.JTextField jtxtNomeFantasia;
    private javax.swing.JTextField jtxtPesquisa;
    private javax.swing.JTextField jtxtRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
