/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormPrincipal extends javax.swing.JFrame {
    
    public static boolean uploadDisponivel = true;
    public static com.sys.Notification notificacao = com.sys.Notification.getInstance();
    
    public static FormGerenciarGrupo fGerenciarGrupo = new FormGerenciarGrupo();
    public static FormGerenciarUsuario fGerenciarUsuario = new FormGerenciarUsuario();
    public static FormGerenciarEmpresa fGerenciarEmpresa = new FormGerenciarEmpresa();
    public static FormGerenciarFamilia fGerenciarFamilia = new FormGerenciarFamilia();
    public static FormGerenciarIndividuo fGerenciarIndividuo = new FormGerenciarIndividuo();
    public static FormGerenciarImovel fGerenciarImovel = new FormGerenciarImovel();
    public static FormGerenciarNucleo fGerenciarNucleo = new FormGerenciarNucleo();
    public static FormGerenciarRecursoMobilidade fGerenciarRecursoMobilidade = new FormGerenciarRecursoMobilidade();
    public static FormGerenciarRecursoSocial fGerenciarRecursoSocial = new FormGerenciarRecursoSocial();
    public static FormGerenciarDepartamento fGerenciarSecretaria = new FormGerenciarDepartamento();
    public static FormFerramentaConfigurarServidor fFerramentaConfigurarServidor = new FormFerramentaConfigurarServidor();

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        
        initComponents();
        
        try {
            
            com.sys.SystemSettings.setSystemThemeNimbus();
            
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/img/logo.png"));
        setIconImage(icon.getImage());
        setLocationRelativeTo(null);
        setVisible(true);
        
        if (cadhab.CadHab.usuario == null) {
            
            FormLogon logon = new FormLogon(this, true);
            logon.setVisible(true);
            
        }
        
        if (cadhab.CadHab.usuario != null)
            jlblUsuario.setText(cadhab.CadHab.usuario.getUsuario() + " - " + cadhab.CadHab.usuario.getNome());
        
        notificacao.setIcon(java.awt.Toolkit.getDefaultToolkit().createImage(getClass().getResource("/cadhab/ui/icon/cadhab.png")));
        notificacao.createSystemTray();
        java.lang.Thread thread = new java.lang.Thread(notificacao);
        thread.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdktDesktop = new javax.swing.JDesktopPane();
        jpnlBarraStatus = new javax.swing.JPanel();
        jpnlBarraStatusWrapper = new javax.swing.JPanel();
        jsepStatusServidor = new javax.swing.JSeparator();
        jlblStatusServidor = new javax.swing.JLabel();
        jsepUsuario = new javax.swing.JSeparator();
        jlblUsuario = new javax.swing.JLabel();
        jsepTarefa = new javax.swing.JSeparator();
        jlblTarefa = new javax.swing.JLabel();
        jsepBarraProgresso = new javax.swing.JSeparator();
        jpgbProgresso = new javax.swing.JProgressBar();
        jsepNUM = new javax.swing.JSeparator();
        jlblNUM = new javax.swing.JLabel();
        jsepCAP = new javax.swing.JSeparator();
        jlblCAP = new javax.swing.JLabel();
        jsepINS = new javax.swing.JSeparator();
        jlblINS = new javax.swing.JLabel();
        jmbarSuperior = new javax.swing.JMenuBar();
        jmenPrincipal = new javax.swing.JMenu();
        jmitPrincipalTrocarSenha = new javax.swing.JMenuItem();
        jsepPrincipal = new javax.swing.JPopupMenu.Separator();
        jmitPrincipalLogoff = new javax.swing.JMenuItem();
        jmitPrincipalSair = new javax.swing.JMenuItem();
        jmenGerenciamento = new javax.swing.JMenu();
        jmenGerenciamentoAcesso = new javax.swing.JMenu();
        jmitAcessoGrupo = new javax.swing.JMenuItem();
        jmitAcessoUsuario = new javax.swing.JMenuItem();
        jmenGerenciamentoCadHab = new javax.swing.JMenu();
        jmitCadHabEmpresa = new javax.swing.JMenuItem();
        jmitCadHabFamilia = new javax.swing.JMenuItem();
        jmitCadHabIndividuo = new javax.swing.JMenuItem();
        jmitCadHabImovel = new javax.swing.JMenuItem();
        jmitCadHabNucleo = new javax.swing.JMenuItem();
        jmenGerenciamentoRecurso = new javax.swing.JMenu();
        jmitRecursoMobilidade = new javax.swing.JMenuItem();
        jmitRecursoSocial = new javax.swing.JMenuItem();
        jmitRecursoDepartamento = new javax.swing.JMenuItem();
        jmenRelatorio = new javax.swing.JMenu();
        jmenFerramenta = new javax.swing.JMenu();
        jmitFerramentaConfigurarServidor = new javax.swing.JMenuItem();
        jmenJanela = new javax.swing.JMenu();
        jmitJanelaHorizontalmente = new javax.swing.JMenuItem();
        jmitJanelaVerticalmente = new javax.swing.JMenuItem();
        jmitJanelaCascata = new javax.swing.JMenuItem();
        jsepJanelas = new javax.swing.JPopupMenu.Separator();
        jmitJanelaFecharTodas = new javax.swing.JMenuItem();
        jmenSobre = new javax.swing.JMenu();
        jmenAjuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CadHab - Cadastro Habitacional");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jdktDesktop.setBackground(new java.awt.Color(240, 240, 240));
        jdktDesktop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdktDesktopKeyPressed(evt);
            }
        });

        jpnlBarraStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlBarraStatus.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jpnlBarraStatusComponentResized(evt);
            }
        });
        jpnlBarraStatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpnlBarraStatusKeyPressed(evt);
            }
        });
        jpnlBarraStatus.setLayout(null);

        jpnlBarraStatusWrapper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpnlBarraStatusWrapperKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.setLayout(null);

        jsepStatusServidor.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jsepStatusServidor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jsepStatusServidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepStatusServidorKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jsepStatusServidor);
        jsepStatusServidor.setBounds(3, 0, 25, 25);

        jlblStatusServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/server.png"))); // NOI18N
        jlblStatusServidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlblStatusServidorKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jlblStatusServidor);
        jlblStatusServidor.setBounds(5, 2, 20, 20);

        jsepUsuario.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jsepUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jsepUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepUsuarioKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jsepUsuario);
        jsepUsuario.setBounds(29, 0, 400, 25);

        jlblUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblUsuario.setText("Usuário");
        jlblUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlblUsuarioKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jlblUsuario);
        jlblUsuario.setBounds(33, 0, 390, 25);

        jsepTarefa.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jsepTarefa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jsepTarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepTarefaKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jsepTarefa);
        jsepTarefa.setBounds(430, 0, 332, 25);

        jlblTarefa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblTarefa.setText("Pronto.");
        jlblTarefa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlblTarefaKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jlblTarefa);
        jlblTarefa.setBounds(434, 0, 323, 25);

        jsepBarraProgresso.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jsepBarraProgresso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jsepBarraProgresso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepBarraProgressoKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jsepBarraProgresso);
        jsepBarraProgresso.setBounds(763, 0, 150, 25);

        jpgbProgresso.setFocusable(false);
        jpgbProgresso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpgbProgressoKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jpgbProgresso);
        jpgbProgresso.setBounds(768, 5, 140, 15);

        jsepNUM.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jsepNUM.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jsepNUM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepNUMKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jsepNUM);
        jsepNUM.setBounds(914, 0, 35, 25);

        jlblNUM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNUM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNUM.setText("NUM");
        jlblNUM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblNUM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlblNUMKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jlblNUM);
        jlblNUM.setBounds(919, 0, 25, 25);

        jsepCAP.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jsepCAP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jsepCAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepCAPKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jsepCAP);
        jsepCAP.setBounds(950, 0, 35, 25);

        jlblCAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblCAP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCAP.setText("CAP");
        jlblCAP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblCAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlblCAPKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jlblCAP);
        jlblCAP.setBounds(955, 0, 25, 25);

        jsepINS.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jsepINS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jsepINS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepINSKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jsepINS);
        jsepINS.setBounds(986, 0, 35, 25);

        jlblINS.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblINS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblINS.setText("INS");
        jlblINS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlblINS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlblINSKeyPressed(evt);
            }
        });
        jpnlBarraStatusWrapper.add(jlblINS);
        jlblINS.setBounds(990, 0, 25, 25);

        jpnlBarraStatus.add(jpnlBarraStatusWrapper);
        jpnlBarraStatusWrapper.setBounds(0, 0, 1021, 25);

        jmbarSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jmbarSuperior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmbarSuperiorKeyPressed(evt);
            }
        });

        jmenPrincipal.setText("Principal");
        jmenPrincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenPrincipalKeyPressed(evt);
            }
        });

        jmitPrincipalTrocarSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitPrincipalTrocarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/password.png"))); // NOI18N
        jmitPrincipalTrocarSenha.setText("Mudar Minha Senha");
        jmitPrincipalTrocarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitPrincipalTrocarSenhaKeyPressed(evt);
            }
        });
        jmenPrincipal.add(jmitPrincipalTrocarSenha);

        jsepPrincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepPrincipalKeyPressed(evt);
            }
        });
        jmenPrincipal.add(jsepPrincipal);

        jmitPrincipalLogoff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmitPrincipalLogoff.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitPrincipalLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/logoff.png"))); // NOI18N
        jmitPrincipalLogoff.setText("Logoff");
        jmitPrincipalLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitPrincipalLogoffActionPerformed(evt);
            }
        });
        jmitPrincipalLogoff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitPrincipalLogoffKeyPressed(evt);
            }
        });
        jmenPrincipal.add(jmitPrincipalLogoff);

        jmitPrincipalSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmitPrincipalSair.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitPrincipalSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/exit.png"))); // NOI18N
        jmitPrincipalSair.setText("Sair");
        jmitPrincipalSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitPrincipalSairActionPerformed(evt);
            }
        });
        jmitPrincipalSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitPrincipalSairKeyPressed(evt);
            }
        });
        jmenPrincipal.add(jmitPrincipalSair);

        jmbarSuperior.add(jmenPrincipal);

        jmenGerenciamento.setText("Gerenciamento");
        jmenGerenciamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenGerenciamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenGerenciamentoKeyPressed(evt);
            }
        });

        jmenGerenciamentoAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/door.png"))); // NOI18N
        jmenGerenciamentoAcesso.setText("Acesso");
        jmenGerenciamentoAcesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenGerenciamentoAcesso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenGerenciamentoAcessoKeyPressed(evt);
            }
        });

        jmitAcessoGrupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jmitAcessoGrupo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitAcessoGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/group.png"))); // NOI18N
        jmitAcessoGrupo.setText("Grupo");
        jmitAcessoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitAcessoGrupoActionPerformed(evt);
            }
        });
        jmitAcessoGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitAcessoGrupoKeyPressed(evt);
            }
        });
        jmenGerenciamentoAcesso.add(jmitAcessoGrupo);

        jmitAcessoUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jmitAcessoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitAcessoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/user.png"))); // NOI18N
        jmitAcessoUsuario.setText("Usuário");
        jmitAcessoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitAcessoUsuarioActionPerformed(evt);
            }
        });
        jmitAcessoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitAcessoUsuarioKeyPressed(evt);
            }
        });
        jmenGerenciamentoAcesso.add(jmitAcessoUsuario);

        jmenGerenciamento.add(jmenGerenciamentoAcesso);

        jmenGerenciamentoCadHab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/cadhab.png"))); // NOI18N
        jmenGerenciamentoCadHab.setText("CadHab");
        jmenGerenciamentoCadHab.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenGerenciamentoCadHab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenGerenciamentoCadHabKeyPressed(evt);
            }
        });

        jmitCadHabEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmitCadHabEmpresa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitCadHabEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/building.png"))); // NOI18N
        jmitCadHabEmpresa.setText("Empresa");
        jmitCadHabEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitCadHabEmpresaActionPerformed(evt);
            }
        });
        jmitCadHabEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitCadHabEmpresaKeyPressed(evt);
            }
        });
        jmenGerenciamentoCadHab.add(jmitCadHabEmpresa);

        jmitCadHabFamilia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jmitCadHabFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitCadHabFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/family.png"))); // NOI18N
        jmitCadHabFamilia.setText("Família");
        jmitCadHabFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitCadHabFamiliaActionPerformed(evt);
            }
        });
        jmitCadHabFamilia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitCadHabFamiliaKeyPressed(evt);
            }
        });
        jmenGerenciamentoCadHab.add(jmitCadHabFamilia);

        jmitCadHabIndividuo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jmitCadHabIndividuo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitCadHabIndividuo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/subject.png"))); // NOI18N
        jmitCadHabIndividuo.setText("Indivíduo");
        jmitCadHabIndividuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitCadHabIndividuoActionPerformed(evt);
            }
        });
        jmitCadHabIndividuo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitCadHabIndividuoKeyPressed(evt);
            }
        });
        jmenGerenciamentoCadHab.add(jmitCadHabIndividuo);

        jmitCadHabImovel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jmitCadHabImovel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitCadHabImovel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/house.png"))); // NOI18N
        jmitCadHabImovel.setText("Imóvel");
        jmitCadHabImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitCadHabImovelActionPerformed(evt);
            }
        });
        jmitCadHabImovel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitCadHabImovelKeyPressed(evt);
            }
        });
        jmenGerenciamentoCadHab.add(jmitCadHabImovel);

        jmitCadHabNucleo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jmitCadHabNucleo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitCadHabNucleo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/centre.png"))); // NOI18N
        jmitCadHabNucleo.setText("Núcleo");
        jmitCadHabNucleo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitCadHabNucleoActionPerformed(evt);
            }
        });
        jmitCadHabNucleo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitCadHabNucleoKeyPressed(evt);
            }
        });
        jmenGerenciamentoCadHab.add(jmitCadHabNucleo);

        jmenGerenciamento.add(jmenGerenciamentoCadHab);

        jmenGerenciamentoRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/brick.png"))); // NOI18N
        jmenGerenciamentoRecurso.setText("Recursos");
        jmenGerenciamentoRecurso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenGerenciamentoRecurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenGerenciamentoRecursoKeyPressed(evt);
            }
        });

        jmitRecursoMobilidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitRecursoMobilidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/ways.png"))); // NOI18N
        jmitRecursoMobilidade.setText("Recurso de Acesso");
        jmitRecursoMobilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitRecursoMobilidadeActionPerformed(evt);
            }
        });
        jmitRecursoMobilidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitRecursoMobilidadeKeyPressed(evt);
            }
        });
        jmenGerenciamentoRecurso.add(jmitRecursoMobilidade);

        jmitRecursoSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitRecursoSocial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/building.png"))); // NOI18N
        jmitRecursoSocial.setText("Recurso Social");
        jmitRecursoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitRecursoSocialActionPerformed(evt);
            }
        });
        jmitRecursoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitRecursoSocialKeyPressed(evt);
            }
        });
        jmenGerenciamentoRecurso.add(jmitRecursoSocial);

        jmitRecursoDepartamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitRecursoDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/secretary.png"))); // NOI18N
        jmitRecursoDepartamento.setText("Secretaria");
        jmitRecursoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitRecursoDepartamentoActionPerformed(evt);
            }
        });
        jmitRecursoDepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitRecursoDepartamentoKeyPressed(evt);
            }
        });
        jmenGerenciamentoRecurso.add(jmitRecursoDepartamento);

        jmenGerenciamento.add(jmenGerenciamentoRecurso);

        jmbarSuperior.add(jmenGerenciamento);

        jmenRelatorio.setText("Relatórios");
        jmenRelatorio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenRelatorio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenRelatorioKeyPressed(evt);
            }
        });
        jmbarSuperior.add(jmenRelatorio);

        jmenFerramenta.setText("Ferramentas");
        jmenFerramenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenFerramenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenFerramentaKeyPressed(evt);
            }
        });

        jmitFerramentaConfigurarServidor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitFerramentaConfigurarServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/server.png"))); // NOI18N
        jmitFerramentaConfigurarServidor.setText("Configurações do Servidor");
        jmitFerramentaConfigurarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitFerramentaConfigurarServidorActionPerformed(evt);
            }
        });
        jmitFerramentaConfigurarServidor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitFerramentaConfigurarServidorKeyPressed(evt);
            }
        });
        jmenFerramenta.add(jmitFerramentaConfigurarServidor);

        jmbarSuperior.add(jmenFerramenta);

        jmenJanela.setText("Janelas");
        jmenJanela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenJanela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenJanelaKeyPressed(evt);
            }
        });

        jmitJanelaHorizontalmente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitJanelaHorizontalmente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/windowhorizontal.png"))); // NOI18N
        jmitJanelaHorizontalmente.setText("Organizar Horizontalmente");
        jmitJanelaHorizontalmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitJanelaHorizontalmenteActionPerformed(evt);
            }
        });
        jmitJanelaHorizontalmente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitJanelaHorizontalmenteKeyPressed(evt);
            }
        });
        jmenJanela.add(jmitJanelaHorizontalmente);

        jmitJanelaVerticalmente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitJanelaVerticalmente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/windowvertical.png"))); // NOI18N
        jmitJanelaVerticalmente.setText("Organizar Verticalmente");
        jmitJanelaVerticalmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitJanelaVerticalmenteActionPerformed(evt);
            }
        });
        jmitJanelaVerticalmente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitJanelaVerticalmenteKeyPressed(evt);
            }
        });
        jmenJanela.add(jmitJanelaVerticalmente);

        jmitJanelaCascata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitJanelaCascata.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/windowcascade.png"))); // NOI18N
        jmitJanelaCascata.setText("Organizar em Cascata");
        jmitJanelaCascata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitJanelaCascataActionPerformed(evt);
            }
        });
        jmitJanelaCascata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitJanelaCascataKeyPressed(evt);
            }
        });
        jmenJanela.add(jmitJanelaCascata);

        jsepJanelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsepJanelasKeyPressed(evt);
            }
        });
        jmenJanela.add(jsepJanelas);

        jmitJanelaFecharTodas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmitJanelaFecharTodas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/windowclose.png"))); // NOI18N
        jmitJanelaFecharTodas.setText("Fechar Todas as Janelas");
        jmitJanelaFecharTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitJanelaFecharTodasActionPerformed(evt);
            }
        });
        jmitJanelaFecharTodas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmitJanelaFecharTodasKeyPressed(evt);
            }
        });
        jmenJanela.add(jmitJanelaFecharTodas);

        jmbarSuperior.add(jmenJanela);

        jmenSobre.setText("Sobre");
        jmenSobre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenSobre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenSobreKeyPressed(evt);
            }
        });
        jmbarSuperior.add(jmenSobre);

        jmenAjuda.setText("Ajuda");
        jmenAjuda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmenAjuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmenAjudaKeyPressed(evt);
            }
        });
        jmbarSuperior.add(jmenAjuda);

        setJMenuBar(jmbarSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdktDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
            .addComponent(jpnlBarraStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdktDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlBarraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmitCadHabNucleoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitCadHabNucleoActionPerformed
        
        if (fGerenciarNucleo.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarNucleo);
            fGerenciarNucleo.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitCadHabNucleoActionPerformed

    private void jmitCadHabImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitCadHabImovelActionPerformed
        
        if (fGerenciarImovel.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarImovel);
            fGerenciarImovel.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitCadHabImovelActionPerformed

    private void jmitCadHabIndividuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitCadHabIndividuoActionPerformed
        
        if (fGerenciarIndividuo.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarIndividuo);
            fGerenciarIndividuo.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitCadHabIndividuoActionPerformed

    private void jmitRecursoMobilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitRecursoMobilidadeActionPerformed
        
        if (fGerenciarRecursoMobilidade.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarRecursoMobilidade);
            fGerenciarRecursoMobilidade.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitRecursoMobilidadeActionPerformed

    private void jmitRecursoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitRecursoSocialActionPerformed
        
        if (fGerenciarRecursoSocial.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarRecursoSocial);
            fGerenciarRecursoSocial.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitRecursoSocialActionPerformed

    private void jmitCadHabFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitCadHabFamiliaActionPerformed
        
        if (fGerenciarFamilia.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarFamilia);
            fGerenciarFamilia.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitCadHabFamiliaActionPerformed

    private void jmitCadHabEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitCadHabEmpresaActionPerformed
        
        if (fGerenciarEmpresa.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarEmpresa);
            fGerenciarEmpresa.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitCadHabEmpresaActionPerformed

    private void jmitJanelaCascataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitJanelaCascataActionPerformed
        
        try {
            
            javax.swing.JInternalFrame[] frames = jdktDesktop.getAllFrames();
            int width = 0;
            int height = 0;
            java.awt.Dimension dimension = null;

            for (short i = 0; i < frames.length; i++) {
                
                if (frames[i].isIcon())
                    frames[i].setIcon(false);
                
                dimension = frames[i].getPreferredSize();
                frames[i].setBounds(width, height, (int) java.lang.Math.round(dimension.getWidth()), (int) java.lang.Math.round(dimension.getHeight()));
                frames[i].moveToFront();
                width = height += 25;
                
            }
        
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }//GEN-LAST:event_jmitJanelaCascataActionPerformed

    private void jmitAcessoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitAcessoGrupoActionPerformed
        
        if (fGerenciarGrupo.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarGrupo);
            fGerenciarGrupo.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitAcessoGrupoActionPerformed

    private void jmitAcessoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitAcessoUsuarioActionPerformed
        
        if (fGerenciarUsuario.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarUsuario);
            fGerenciarUsuario.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitAcessoUsuarioActionPerformed

    private void jmitRecursoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitRecursoDepartamentoActionPerformed
        
        if (fGerenciarSecretaria.getDesktopPane() == null) {
            
            jdktDesktop.add(fGerenciarSecretaria);
            fGerenciarSecretaria.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitRecursoDepartamentoActionPerformed

    private void jmitFerramentaConfigurarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitFerramentaConfigurarServidorActionPerformed
        
        if (fFerramentaConfigurarServidor.getDesktopPane() == null) {
            
            jdktDesktop.add(fFerramentaConfigurarServidor);
            fFerramentaConfigurarServidor.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitFerramentaConfigurarServidorActionPerformed

    private void jmitPrincipalSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitPrincipalSairActionPerformed
        
        java.lang.Object[] options = {"Sim", "Não"};
        java.lang.Object opcao = javax.swing.JOptionPane.showOptionDialog(this, "Deseja realmente sair do sistema?", "Confirmação",
                javax.swing.JOptionPane.DEFAULT_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null,
                options, options[1]);
            
        if (opcao.toString().equals("0")) {
                
            System.exit(0);
            
        }
        
    }//GEN-LAST:event_jmitPrincipalSairActionPerformed

    private void jmitPrincipalLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitPrincipalLogoffActionPerformed
        
        java.lang.Object[] options = {"Sim", "Não"};
        java.lang.Object opcao = javax.swing.JOptionPane.showOptionDialog(this, "Deseja realmente fazer logoff do sistema?", "Confirmação",
                javax.swing.JOptionPane.DEFAULT_OPTION, javax.swing.JOptionPane.QUESTION_MESSAGE, null,
                options, options[1]);
            
        if (opcao.toString().equals("0")) {
                
            javax.swing.JInternalFrame[] frames = jdktDesktop.getAllFrames();
            
            for (int i = 0; i < frames.length; i++) {
                
                frames[i].dispose();
                
            }
            
            cadhab.CadHab.usuario = null;
            FormLogon logon = new FormLogon(this, true);
            logon.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jmitPrincipalLogoffActionPerformed

    private void jmitJanelaFecharTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitJanelaFecharTodasActionPerformed
        
        javax.swing.JInternalFrame[] janelas = jdktDesktop.getAllFrames();
        
        for (int i = 0; i < janelas.length; i++)
            janelas[i].dispose();
        
    }//GEN-LAST:event_jmitJanelaFecharTodasActionPerformed

    private void jpnlBarraStatusComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jpnlBarraStatusComponentResized
        
        jpnlBarraStatusWrapper.setSize(1020, 25);
        int parentWidth = jpnlBarraStatus.getWidth();
        int childWidth = jpnlBarraStatusWrapper.getWidth();
        int newLocation = java.lang.Math.round((parentWidth - childWidth) / 2);
        jpnlBarraStatusWrapper.setBounds(newLocation, 0, 1020, jpnlBarraStatusWrapper.getHeight());
        
    }//GEN-LAST:event_jpnlBarraStatusComponentResized

    private void jmitJanelaHorizontalmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitJanelaHorizontalmenteActionPerformed
        
        try {
            
            javax.swing.JInternalFrame[] frames = jdktDesktop.getAllFrames();
            int mainWidth = jdktDesktop.getWidth();
            int windowWidth = mainWidth / frames.length;

            int width = 0;

            for (short i = 0; i < frames.length; i++) {
                
                if (frames[i].isIcon())
                    frames[i].setIcon(false);
                
                frames[i].setBounds(width, 0, windowWidth, jdktDesktop.getHeight());
                width += windowWidth;
                
            }
        
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }//GEN-LAST:event_jmitJanelaHorizontalmenteActionPerformed

    private void jmitJanelaVerticalmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitJanelaVerticalmenteActionPerformed
        
        try {
            
            javax.swing.JInternalFrame[] frames = jdktDesktop.getAllFrames();
            int mainHeight = jdktDesktop.getHeight();
            int windowHeight = mainHeight / frames.length;

            int height = 0;

            for (short i = 0; i < frames.length; i++) {
                
                if (frames[i].isIcon())
                    frames[i].setIcon(false);
                
                frames[i].setBounds(0, height, jdktDesktop.getWidth(), windowHeight);
                height += windowHeight;
                
            }
        
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }//GEN-LAST:event_jmitJanelaVerticalmenteActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_formKeyPressed

    private void jdktDesktopKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdktDesktopKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jdktDesktopKeyPressed

    private void jpnlBarraStatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpnlBarraStatusKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jpnlBarraStatusKeyPressed

    private void jpnlBarraStatusWrapperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpnlBarraStatusWrapperKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jpnlBarraStatusWrapperKeyPressed

    private void jsepStatusServidorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepStatusServidorKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepStatusServidorKeyPressed

    private void jlblStatusServidorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlblStatusServidorKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jlblStatusServidorKeyPressed

    private void jsepUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepUsuarioKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepUsuarioKeyPressed

    private void jlblUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlblUsuarioKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jlblUsuarioKeyPressed

    private void jsepTarefaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepTarefaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepTarefaKeyPressed

    private void jlblTarefaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlblTarefaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jlblTarefaKeyPressed

    private void jsepBarraProgressoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepBarraProgressoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepBarraProgressoKeyPressed

    private void jpgbProgressoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpgbProgressoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jpgbProgressoKeyPressed

    private void jsepNUMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepNUMKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepNUMKeyPressed

    private void jlblNUMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlblNUMKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jlblNUMKeyPressed

    private void jsepCAPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepCAPKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepCAPKeyPressed

    private void jlblCAPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlblCAPKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jlblCAPKeyPressed

    private void jsepINSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepINSKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepINSKeyPressed

    private void jlblINSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlblINSKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jlblINSKeyPressed

    private void jmbarSuperiorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmbarSuperiorKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmbarSuperiorKeyPressed

    private void jmenPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenPrincipalKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenPrincipalKeyPressed

    private void jmitPrincipalTrocarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitPrincipalTrocarSenhaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitPrincipalTrocarSenhaKeyPressed

    private void jsepPrincipalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepPrincipalKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepPrincipalKeyPressed

    private void jmitPrincipalLogoffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitPrincipalLogoffKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitPrincipalLogoffKeyPressed

    private void jmitPrincipalSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitPrincipalSairKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitPrincipalSairKeyPressed

    private void jmenGerenciamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenGerenciamentoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenGerenciamentoKeyPressed

    private void jmenGerenciamentoAcessoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenGerenciamentoAcessoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenGerenciamentoAcessoKeyPressed

    private void jmitAcessoGrupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitAcessoGrupoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitAcessoGrupoKeyPressed

    private void jmitAcessoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitAcessoUsuarioKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitAcessoUsuarioKeyPressed

    private void jmenGerenciamentoCadHabKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenGerenciamentoCadHabKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenGerenciamentoCadHabKeyPressed

    private void jmitCadHabEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitCadHabEmpresaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitCadHabEmpresaKeyPressed

    private void jmitCadHabFamiliaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitCadHabFamiliaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitCadHabFamiliaKeyPressed

    private void jmitCadHabIndividuoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitCadHabIndividuoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitCadHabIndividuoKeyPressed

    private void jmitCadHabImovelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitCadHabImovelKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitCadHabImovelKeyPressed

    private void jmitCadHabNucleoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitCadHabNucleoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitCadHabNucleoKeyPressed

    private void jmenGerenciamentoRecursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenGerenciamentoRecursoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenGerenciamentoRecursoKeyPressed

    private void jmitRecursoMobilidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitRecursoMobilidadeKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitRecursoMobilidadeKeyPressed

    private void jmitRecursoSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitRecursoSocialKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitRecursoSocialKeyPressed

    private void jmitRecursoDepartamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitRecursoDepartamentoKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitRecursoDepartamentoKeyPressed

    private void jmenRelatorioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenRelatorioKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenRelatorioKeyPressed

    private void jmenFerramentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenFerramentaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenFerramentaKeyPressed

    private void jmitFerramentaConfigurarServidorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitFerramentaConfigurarServidorKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitFerramentaConfigurarServidorKeyPressed

    private void jmenJanelaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenJanelaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenJanelaKeyPressed

    private void jmitJanelaHorizontalmenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitJanelaHorizontalmenteKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitJanelaHorizontalmenteKeyPressed

    private void jmitJanelaVerticalmenteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitJanelaVerticalmenteKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitJanelaVerticalmenteKeyPressed

    private void jmitJanelaCascataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitJanelaCascataKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitJanelaCascataKeyPressed

    private void jsepJanelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsepJanelasKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jsepJanelasKeyPressed

    private void jmitJanelaFecharTodasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmitJanelaFecharTodasKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmitJanelaFecharTodasKeyPressed

    private void jmenSobreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenSobreKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenSobreKeyPressed

    private void jmenAjudaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmenAjudaKeyPressed
        
        toogleKeys();
        
    }//GEN-LAST:event_jmenAjudaKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        toogleKeys();
        
    }//GEN-LAST:event_formWindowActivated

    public static void toogleKeys() {
        
        if (java.awt.Toolkit.getDefaultToolkit().getLockingKeyState(java.awt.event.KeyEvent.VK_NUM_LOCK))
            jlblNUM.setText("NUM");
        else 
            jlblNUM.setText("");
        
        if (java.awt.Toolkit.getDefaultToolkit().getLockingKeyState(java.awt.event.KeyEvent.VK_CAPS_LOCK))
            jlblCAP.setText("CAP");
        else 
            jlblCAP.setText("");
        
//        if (java.awt.Toolkit.getDefaultToolkit().getLockingKeyState(java.awt.event.KeyEvent.VK_INSERT))
//            jlblINS.setText("INS");
//        else 
//            jlblINS.setText("");
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdktDesktop;
    private static javax.swing.JLabel jlblCAP;
    private static javax.swing.JLabel jlblINS;
    private static javax.swing.JLabel jlblNUM;
    private javax.swing.JLabel jlblStatusServidor;
    public static javax.swing.JLabel jlblTarefa;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JMenuBar jmbarSuperior;
    private javax.swing.JMenu jmenAjuda;
    private javax.swing.JMenu jmenFerramenta;
    private javax.swing.JMenu jmenGerenciamento;
    private javax.swing.JMenu jmenGerenciamentoAcesso;
    private javax.swing.JMenu jmenGerenciamentoCadHab;
    private javax.swing.JMenu jmenGerenciamentoRecurso;
    private javax.swing.JMenu jmenJanela;
    private javax.swing.JMenu jmenPrincipal;
    private javax.swing.JMenu jmenRelatorio;
    private javax.swing.JMenu jmenSobre;
    private javax.swing.JMenuItem jmitAcessoGrupo;
    private javax.swing.JMenuItem jmitAcessoUsuario;
    private javax.swing.JMenuItem jmitCadHabEmpresa;
    private javax.swing.JMenuItem jmitCadHabFamilia;
    private javax.swing.JMenuItem jmitCadHabImovel;
    private javax.swing.JMenuItem jmitCadHabIndividuo;
    private javax.swing.JMenuItem jmitCadHabNucleo;
    private javax.swing.JMenuItem jmitFerramentaConfigurarServidor;
    private javax.swing.JMenuItem jmitJanelaCascata;
    private javax.swing.JMenuItem jmitJanelaFecharTodas;
    private javax.swing.JMenuItem jmitJanelaHorizontalmente;
    private javax.swing.JMenuItem jmitJanelaVerticalmente;
    private javax.swing.JMenuItem jmitPrincipalLogoff;
    private javax.swing.JMenuItem jmitPrincipalSair;
    private javax.swing.JMenuItem jmitPrincipalTrocarSenha;
    private javax.swing.JMenuItem jmitRecursoDepartamento;
    private javax.swing.JMenuItem jmitRecursoMobilidade;
    private javax.swing.JMenuItem jmitRecursoSocial;
    public static javax.swing.JProgressBar jpgbProgresso;
    private javax.swing.JPanel jpnlBarraStatus;
    private javax.swing.JPanel jpnlBarraStatusWrapper;
    private javax.swing.JSeparator jsepBarraProgresso;
    private javax.swing.JSeparator jsepCAP;
    private javax.swing.JSeparator jsepINS;
    private javax.swing.JPopupMenu.Separator jsepJanelas;
    private javax.swing.JSeparator jsepNUM;
    private javax.swing.JPopupMenu.Separator jsepPrincipal;
    private javax.swing.JSeparator jsepStatusServidor;
    private javax.swing.JSeparator jsepTarefa;
    private javax.swing.JSeparator jsepUsuario;
    // End of variables declaration//GEN-END:variables
}
