/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author 14145
 */
public class FormGerenciarTelefoneIndividuo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGerenciarTelefoneIndividuo
     */
    public FormGerenciarTelefoneIndividuo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPrincipal = new javax.swing.JPanel();
        jlblIndividuo = new javax.swing.JLabel();
        jtxtIdIndividuo = new javax.swing.JTextField();
        jtxtNomeIndividuo = new javax.swing.JTextField();
        jlblTipo = new javax.swing.JLabel();
        jcbbTipo = new javax.swing.JComboBox();
        jlblNumero = new javax.swing.JLabel();
        jtxtNumero = new javax.swing.JFormattedTextField();
        jsepRodape = new javax.swing.JSeparator();
        jbtnNovo = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CadHab - Gerenciamento de Telefones do Indivíduo");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/telephone.png"))); // NOI18N

        jpnlPrincipal.setLayout(null);

        jlblIndividuo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblIndividuo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblIndividuo.setText("Indivíduo:");
        jpnlPrincipal.add(jlblIndividuo);
        jlblIndividuo.setBounds(10, 10, 70, 25);

        jtxtIdIndividuo.setEditable(false);
        jtxtIdIndividuo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtIdIndividuo);
        jtxtIdIndividuo.setBounds(90, 10, 120, 25);

        jtxtNomeIndividuo.setEditable(false);
        jtxtNomeIndividuo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtNomeIndividuo);
        jtxtNomeIndividuo.setBounds(90, 40, 430, 25);

        jlblTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblTipo.setText("Tipo:");
        jpnlPrincipal.add(jlblTipo);
        jlblTipo.setBounds(10, 70, 70, 25);

        jcbbTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Sim", "Não" }));
        jpnlPrincipal.add(jcbbTipo);
        jcbbTipo.setBounds(90, 70, 430, 25);

        jlblNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblNumero.setText("Número:");
        jpnlPrincipal.add(jlblNumero);
        jlblNumero.setBounds(10, 100, 70, 25);

        jtxtNumero.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jtxtNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtNumero);
        jtxtNumero.setBounds(90, 100, 430, 25);
        jpnlPrincipal.add(jsepRodape);
        jsepRodape.setBounds(10, 140, 510, 2);

        jbtnNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/new.png"))); // NOI18N
        jbtnNovo.setText("Novo");
        jbtnNovo.setIconTextGap(10);
        jpnlPrincipal.add(jbtnNovo);
        jbtnNovo.setBounds(10, 150, 120, 30);

        jbtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/save.png"))); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setIconTextGap(10);
        jpnlPrincipal.add(jbtnSalvar);
        jbtnSalvar.setBounds(140, 150, 120, 30);

        jbtnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/edit.png"))); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.setIconTextGap(10);
        jpnlPrincipal.add(jbtnEditar);
        jbtnEditar.setBounds(270, 150, 120, 30);

        jbtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/delete.png"))); // NOI18N
        jbtnExcluir.setText("Excluir");
        jbtnExcluir.setIconTextGap(10);
        jpnlPrincipal.add(jbtnExcluir);
        jbtnExcluir.setBounds(400, 150, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox jcbbTipo;
    private javax.swing.JLabel jlblIndividuo;
    private javax.swing.JLabel jlblNumero;
    private javax.swing.JLabel jlblTipo;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JSeparator jsepRodape;
    private javax.swing.JTextField jtxtIdIndividuo;
    private javax.swing.JTextField jtxtNomeIndividuo;
    private javax.swing.JFormattedTextField jtxtNumero;
    // End of variables declaration//GEN-END:variables
}
