/*
 * Classe pertencente ao módulo de GUI do sistema "CadHab".
 */
package cadhab.ui;

/**
 *
 * @author William Oliveira
 * 
 * @version 1.0
 */
public class FormGerenciarFamilia extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormGerenciarFamilia
     */
    public FormGerenciarFamilia() {
        
        initComponents();
        
        try {
            
            com.sys.SystemSettings.setSystemThemeNimbus();
            
        } catch (java.lang.Exception ex) {
            
            ex.printStackTrace();
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPrincipal = new javax.swing.JPanel();
        jpnlTabelaPesquisa = new javax.swing.JPanel();
        jscpTabelaPesquisa = new javax.swing.JScrollPane();
        jtblPesquisa = new javax.swing.JTable();
        jlblRemocaoFamilia = new javax.swing.JLabel();
        jcbbRemocaoFamilia = new javax.swing.JComboBox();
        jlblSituacaoRemocao = new javax.swing.JLabel();
        jtxtSituacaoRemocao = new javax.swing.JTextField();
        jlblEspecifiqueRemocao = new javax.swing.JLabel();
        jtxtEspecifiqueRemocao = new javax.swing.JTextField();
        jlblAtendente = new javax.swing.JLabel();
        jtxtAtendente = new javax.swing.JTextField();
        jlblDataAtendimento = new javax.swing.JLabel();
        jtxtDataAtendimento = new javax.swing.JFormattedTextField();
        jlblAtualizadoPor = new javax.swing.JLabel();
        jtxtAtualizadoPor = new javax.swing.JTextField();
        jlblDataAtualizacao = new javax.swing.JLabel();
        jtxtDataAtualizacao = new javax.swing.JFormattedTextField();
        jsepRodape = new javax.swing.JSeparator();
        jbtnNovo = new javax.swing.JButton();
        jbtnSalvar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("CadHab - Gerenciamento de Famílias");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/family.png"))); // NOI18N

        jpnlPrincipal.setLayout(null);

        jtblPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtblPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jscpTabelaPesquisa.setViewportView(jtblPesquisa);

        javax.swing.GroupLayout jpnlTabelaPesquisaLayout = new javax.swing.GroupLayout(jpnlTabelaPesquisa);
        jpnlTabelaPesquisa.setLayout(jpnlTabelaPesquisaLayout);
        jpnlTabelaPesquisaLayout.setHorizontalGroup(
            jpnlTabelaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTabelaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        jpnlTabelaPesquisaLayout.setVerticalGroup(
            jpnlTabelaPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscpTabelaPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );

        jpnlPrincipal.add(jpnlTabelaPesquisa);
        jpnlTabelaPesquisa.setBounds(10, 10, 760, 200);

        jlblRemocaoFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblRemocaoFamilia.setText("Remoção Família:");
        jpnlPrincipal.add(jlblRemocaoFamilia);
        jlblRemocaoFamilia.setBounds(10, 220, 120, 25);

        jcbbRemocaoFamilia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbbRemocaoFamilia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Sim", "Não" }));
        jpnlPrincipal.add(jcbbRemocaoFamilia);
        jcbbRemocaoFamilia.setBounds(130, 220, 640, 25);

        jlblSituacaoRemocao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblSituacaoRemocao.setText("Situação Remoção:");
        jpnlPrincipal.add(jlblSituacaoRemocao);
        jlblSituacaoRemocao.setBounds(10, 250, 120, 25);

        jtxtSituacaoRemocao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtSituacaoRemocao);
        jtxtSituacaoRemocao.setBounds(130, 250, 640, 25);

        jlblEspecifiqueRemocao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblEspecifiqueRemocao.setText("Especifique:");
        jpnlPrincipal.add(jlblEspecifiqueRemocao);
        jlblEspecifiqueRemocao.setBounds(10, 280, 120, 25);

        jtxtEspecifiqueRemocao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtEspecifiqueRemocao);
        jtxtEspecifiqueRemocao.setBounds(130, 280, 640, 25);

        jlblAtendente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblAtendente.setText("Atendente:");
        jpnlPrincipal.add(jlblAtendente);
        jlblAtendente.setBounds(10, 310, 120, 25);

        jtxtAtendente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtAtendente);
        jtxtAtendente.setBounds(130, 310, 640, 25);

        jlblDataAtendimento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDataAtendimento.setText("Data atendimento:");
        jpnlPrincipal.add(jlblDataAtendimento);
        jlblDataAtendimento.setBounds(10, 340, 120, 25);

        jtxtDataAtendimento.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jpnlPrincipal.add(jtxtDataAtendimento);
        jtxtDataAtendimento.setBounds(130, 340, 640, 25);

        jlblAtualizadoPor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblAtualizadoPor.setText("Atualizado Por:");
        jpnlPrincipal.add(jlblAtualizadoPor);
        jlblAtualizadoPor.setBounds(10, 370, 120, 25);

        jtxtAtualizadoPor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpnlPrincipal.add(jtxtAtualizadoPor);
        jtxtAtualizadoPor.setBounds(130, 370, 640, 25);

        jlblDataAtualizacao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlblDataAtualizacao.setText("Data Atualização:");
        jpnlPrincipal.add(jlblDataAtualizacao);
        jlblDataAtualizacao.setBounds(10, 400, 120, 25);

        jtxtDataAtualizacao.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jpnlPrincipal.add(jtxtDataAtualizacao);
        jtxtDataAtualizacao.setBounds(130, 400, 640, 25);
        jpnlPrincipal.add(jsepRodape);
        jsepRodape.setBounds(10, 440, 760, 2);

        jbtnNovo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/new.png"))); // NOI18N
        jbtnNovo.setText("Novo");
        jbtnNovo.setIconTextGap(10);
        jpnlPrincipal.add(jbtnNovo);
        jbtnNovo.setBounds(260, 450, 120, 30);

        jbtnSalvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/save.png"))); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.setIconTextGap(10);
        jpnlPrincipal.add(jbtnSalvar);
        jbtnSalvar.setBounds(390, 450, 120, 30);

        jbtnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/edit.png"))); // NOI18N
        jbtnEditar.setText("Editar");
        jbtnEditar.setIconTextGap(10);
        jpnlPrincipal.add(jbtnEditar);
        jbtnEditar.setBounds(520, 450, 120, 30);

        jbtnExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cadhab/ui/icon/delete.png"))); // NOI18N
        jbtnExcluir.setText("Excluir");
        jbtnExcluir.setIconTextGap(10);
        jpnlPrincipal.add(jbtnExcluir);
        jbtnExcluir.setBounds(650, 450, 120, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnExcluir;
    private javax.swing.JButton jbtnNovo;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JComboBox jcbbRemocaoFamilia;
    private javax.swing.JLabel jlblAtendente;
    private javax.swing.JLabel jlblAtualizadoPor;
    private javax.swing.JLabel jlblDataAtendimento;
    private javax.swing.JLabel jlblDataAtualizacao;
    private javax.swing.JLabel jlblEspecifiqueRemocao;
    private javax.swing.JLabel jlblRemocaoFamilia;
    private javax.swing.JLabel jlblSituacaoRemocao;
    private javax.swing.JPanel jpnlPrincipal;
    private javax.swing.JPanel jpnlTabelaPesquisa;
    private javax.swing.JScrollPane jscpTabelaPesquisa;
    private javax.swing.JSeparator jsepRodape;
    private javax.swing.JTable jtblPesquisa;
    private javax.swing.JTextField jtxtAtendente;
    private javax.swing.JTextField jtxtAtualizadoPor;
    private javax.swing.JFormattedTextField jtxtDataAtendimento;
    private javax.swing.JFormattedTextField jtxtDataAtualizacao;
    private javax.swing.JTextField jtxtEspecifiqueRemocao;
    private javax.swing.JTextField jtxtSituacaoRemocao;
    // End of variables declaration//GEN-END:variables
}
